/**
 * Document command palette
 *
 * Cmd+P style: a fuzzy-search dialog that filters commands by keyword and runs the selected one on Enter.
 * The command list mirrors the toolbar and keyboard shortcuts.
 */

import type { EditorView } from '@codemirror/view'
import { foldAll, unfoldAll, foldCode, unfoldCode } from '@codemirror/language'
import { openSearchPanel } from '@codemirror/search'
import { gotoLine } from '@codemirror/search'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import i18next from 'i18next'

import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/registry/ui/command'

import { isSpellcheckOn, setSpellcheck } from './extensions/spellcheck'

import {
  insertCallout,
  insertCodeBlock,
  insertComment,
  insertDate,
  insertEmbed,
  insertHighlight,
  insertHorizontalRule,
  insertImage,
  insertLink,
  insertMath,
  insertMathBlock,
  insertTable,
  insertTag,
  insertTimestamp,
  insertWikilink,
  insertFootnote,
  insertAsQuote,
  jumpFootnote,
  jumpToNextHeading,
  jumpToPrevHeading,
  jumpToNextCodeBlock,
  jumpToPrevCodeBlock,
  jumpToNextTask,
  jumpToPrevTask,
  tableToBulletList,
  bulletListToTable,
  renumberFootnotes,
  applySmartArrows,
  applySmartTypography,
  collapseInnerSpaces,
  compressBlankLines,
  convertTabsToSpaces,
  convertSpacesToTabs,
  decodeHtmlEntities,
  dedupSelectedLines,
  deleteCurrentLine,
  duplicateLine,
  ensureFrontmatter,
  ensureReferencesSection,
  generateTOC,
  insertDataviewField,
  insertTodayLink,
  insertTomorrowLink,
  insertYesterdayLink,
  joinLines,
  normalizeBulletMarkers,
  removeEmptyLines,
  renumberOrderedLists,
  reverseLines,
  selectCurrentParagraph,
  selectCurrentSection,
  sortTasks,
  splitSentencesToLines,
  swapLineDown,
  swapLineUp,
  tableMoveColumnLeft,
  tableMoveColumnRight,
  tableMoveRowDown,
  tableMoveRowUp,
  toggleAllTasksInSelection,
  trimTrailingWhitespace,
  wrapAsCodeBlock,
  wrapAsSpoiler,
  convertLinkUnderCursor,
  convertSelectionToCallout,
  cycleListType,
  foldHeadingsBelowLevel,
  moveSectionDown,
  moveSectionUp,
  numberHeadings,
  promoteHeading,
  demoteHeading,
  setLineHeading,
  sortSelectedLines,
  stripFrontmatter,
  stripHeadingNumbers,
  tableAddColumnLeft,
  tableAddColumnRight,
  tableAddRowAbove,
  tableAddRowBelow,
  tableAlignColumn,
  tableDeleteColumn,
  tableDeleteRow,
  tableFormat,
  tableSortByColumn,
  toggleBold,
  toggleBulletList,
  toggleInlineCode,
  toggleItalic,
  toggleOrderedList,
  toggleQuote,
  toggleStrike,
  toggleTaskCheckbox,
  toggleTodoList,
  transformCase,
  unwrapLink,
  wrapAsTag,
  wrapAsWikilink,
  insertSlideBreak,
  jumpToNextSlide,
  jumpToPrevSlide,
  copyCodeBlockAtCursor,
  changeCodeBlockLang,
  shiftAllHeadings,
  copyAsPlainText,
  replaceWithPlain,
  convertCsvSelectionToTable,
  convertTableSelectionToCsv,
  markAllTasks,
  archiveDoneTasks,
  renameDocumentTag,
  convertOutlineSelectionToOpml,
  convertOpmlSelectionToOutline,
  promoteListItem,
  demoteListItem,
  convertBulletListToOrdered,
  convertOrderedListToBullet,
  insertUuid,
  sortFrontmatterKeys,
  toggleFrontmatterKey,
  sortFrontmatterValues,
  slugifyHeadings,
  copyPlainTextOfSelection,
  foldCurrentSection,
  unfoldAllSections,
  selectionToBulletList,
  selectionToOrderedList,
  selectionToTaskList,
  wrapSelectionAsComment,
  unwrapComment,
  swapAdjacentParagraphs,
  showDocumentByteSize,
  convertOrderedToBullet,
  convertBulletToOrdered,
  addBlockquoteAuthor,
  stripBlockquoteAuthor,
  fillEmptyImageAlt,
  expandShortLinksToReference,
  inlineReferenceLinks,
  emojiBullet,
  numberLines,
  unnumberLines,
  cleanTrackingParams,
  decodeUrlsInLinks,
  dedupFrontmatterTags,
  wikilinkToFootnote,
  stripAllImages,
  wrapCodeBlockLang,
  convertSetextHeadings,
  convertAtxToSetext,
  wrapEachLineWith,
  pruneEmptyHeadings,
  annotateCodeLineNumbers,
  boldLargeNumbers,
  insertTaskProgressSummary,
  joinSentences,
  convertSingleQuoteToDouble,
  convertDoubleQuoteToSingle,
  expandWikilinkAliases,
  collapseWikilinkAliases,
  addDaysToDateLinks,
  insertCurrentWeekRange,
  sortListByWordCount,
  splitOnSemicolons,
  normalizeListIndentation,
  escapeMarkdownInPlain,
  splitAfterCjkPunctuation,
  insertAllUrlsList,
  reverseCase,
  tableDedupRowsByFirstColumn,
  tableRotateColumnsLeft,
  tableRotateColumnsRight,
  tableTranspose,
  escapeMarkdownSelection,
  unescapeMarkdownSelection,
  wrapAsDetails,
  convertHeadingsToList,
  convertBulletsToHeadings,
  capitalizeSentences,
  capitalizeEachWord,
  straightToCurlyQuotes,
  curlyToStraightQuotes,
  sortListBlock,
  uniqueListBlock,
  shuffleListBlock,
  moveSectionToTop,
  moveSectionToBottom,
  toggleInlineMath,
  insertHorizontalRuleAtCursor,
  bulletsToCsvLine,
  csvToBulletsLine,
  hardWrapSelection,
  unwrapParagraphs,
  toMarkdownHardBreaks,
  fromMarkdownHardBreaks,
  increaseQuoteLevel,
  decreaseQuoteLevel,
  sortSelectedLinesDesc,
  sortSelectedLinesByLengthAsc,
  sortSelectedLinesByLengthDesc,
  sortSelectedLinesNumericAsc,
  sortSelectedLinesNumericDesc,
  sortSelectedLinesNatural,
  exportOutlineToText,
  trimSectionBlanks,
  insertAuthorAndDateFrontmatter,
  expandSelectionToParagraph,
  selectToNextHeading,
  duplicateCurrentSection,
  mergeAdjacentBlockquotes,
  lowercaseAllHeadings,
  uppercaseAllHeadings,
  convertImagesToWikilinks,
  convertImageWikilinksToMarkdown,
  cleanupZeroWidthChars,
  normalizeUnicodeNFC,
  normalizeUnicodeNFD,
  toggleHighlight,
  transformToSentenceCase,
  unwrapAllLinksToPlainText,
  insertSeparatorComment,
  insertLinksSummary,
  insertTimestampAtCursor,
  wrapAsTimeEntry,
  insertTimeEntriesTotal,
  incrementOrderedListBy,
  prependLinesWith,
  appendLinesWith,
  evalInlineMathInLines,
  cycleTaskStateAtCursor,
  cutCurrentSectionToClipboard,
  stripHighlights,
  stripBold,
  stripItalic,
  stampUpdatedFrontmatter,
  hardBreaksToSpace,
  bulletPairsToDefinitionList,
  sortFrontmatterAliases,
  blockquoteLines,
  unblockquoteLines,
  injectTopTOC,
  changeCalloutTypeAtCursor,
  insertKanbanColumn,
  insertKanbanCard,
  renameInlineDataviewField,
  swapWithNextLine,
  swapWithPrevLine,
  numberFirstCodeBlockLines,
  stripHtmlComments,
  purgeDoneTasksUnderTasksHeading,
  extractWikilinkToOwnLine,
  swapLinkTextWithUrl,
  insertTitledDivider,
  frontmatterFieldInlineToBlock,
  frontmatterFieldBlockToInline,
  swapWikilinkAliasAndTargetAtCursor,
  stampLinesWithDate,
  unwrapDetailsBlocks,
  collapseExcessiveBlankLines,
  singleSpaceAfterListMarker,
  ensureBlankAroundHeadings,
  ensureSingleTrailingNewline,
  sortFrontmatterTopKeys,
  normalizeEmphasisToAsterisk,
  normalizeEmphasisToUnderscore,
  normalizeStrongToAsterisk,
  trimTrailingNonBreakWhitespace,
  fixCommonMarkdownLints,
  splitSectionAtCursor,
  flattenNestedLists,
  indentLinesBySpaces,
  dedentLinesBySpaces,
  plainUrlToAutolink,
  applyFrontmatterTemplate,
  shiftHeadingsUpOneLevel,
  shiftHeadingsDownOneLevel,
  brTagsToHardBreaks,
  wrapSelectionWithPair,
  convertLinksToFootnotes,
  headingsToOutline,
  surroundEachLineWithTag,
  htmlSupToCaret,
  htmlSubToTilde,
  calloutsToHeadings,
  inlineFootnotes,
  insertHashtagStats,
  insertAllLinksReport,
  convertParagraphToFlashcard,
  insertFlashcardSeparator,
  insertDuplicateHeadingsReport,
  lowercaseAllTags,
  uppercaseAllTags,
  paragraphsToHtmlBreaks,
  convertMarkdownImagesToWikiEmbeds,
  convertDocumentEmbedToMdImage,
  setImageWidthForEmbeds,
  injectHtmlAnchorsBeforeHeadings,
  compressTableCellWhitespace,
  abbreviateLinksToHost,
  relativeMdLinksToWikilinks,
  defaultCalloutTitles,
  insertImagesSummary,
  fillImageAltFromFilename,
  insertTodayWikilinkAtCursor,
  normalizeHorizontalRules,
  prefixSectionTasksWithEmoji,
  sortSectionsByHeading,
  tabsToList,
  tidyLinkTextFromSlug,
  paragraphsToQuotes,
  unquoteParagraphs,
  redactSelection,
  insertListSummary,
  surroundSelectionWithPair,
  wikilinksInSectionToFootnotes,
  tagCurrentSection,
  extractTableColumnAsList,
  tableCellsToUpper,
  tableCellsToLower,
  filterListItems,
  keepCheckedTasksOnly,
  removeInlineCodeBackticks,
  singleLineFenceToInline,
  calloutHeaderToHeading,
  inlineMathToBlock,
  wrapSelectionAsAutodetectedCode,
  insertDataviewQuery,
  highlightsToMark,
  markToHighlights,
  normalizeBulletsToDash,
  atxHeadingClose,
  stripAtxClose,
  insertNoteMetadataBlock,
  insertTableEmptyRow,
  annotateWikilinksWithEmoji,
  unifyFrontmatterTags,
  insertScopedTOC,
  promoteH1ToFrontmatterTitle,
  rotateTaskStateAtCursor,
  insertBreadcrumbAtTop,
  splitLongLinesAtSentences,
  dedupAdjacentParagraphs,
  alignImages,
  tagSectionTasks,
  insertTagTree,
  insertMermaidGraphFromSection,
  swapMermaidDirection,
  renameWikilinkInDoc,
  tagsToWikilinks,
  addFrontmatterAlias,
  addReadingCssclass,
  insertSnippet,
  buildReviewNoteSnippet,
  buildMeetingNoteSnippet,
  buildWeeklyReviewSnippet,
  applyColorHighlight,
  swapAdjacentTableColumns,
  insertLightboxImage,
  forceHardBreaks,
  toggleCalloutFold,
  videoLinksToEmbed,
  audioLinksToEmbed,
  insertTemplate,
  inlineDollarToBlock,
  blockDollarToInline,
  appendBlockIdAtCursor,
  incrementBlockIdAtCursor,
  sortLinesByLengthAsc,
  sortLinesByLengthDesc,
  insertDuplicateLinesReport,
  mdImagesToDocumentEmbed,
  documentEmbedToMdImages,
  expandCalloutAliases,
  unwrapSelfLinks,
  filterOutlineByLevel,
  cycleTaskCheckboxAtCursor,
  autoLinkBareUrls,
  insertLoremIpsum,
  titleCaseFrontmatterKeys,
  splitParagraphAtCursor,
  trimHeadingPunctuation,
  splitLongTable,
  swapListItems,
  insertStickyNote,
  embedKnownVideoIframes,
  collapseParagraphAsDetails,
  jumpToNextWikilink,
  jumpToPrevWikilink,
  promoteListIndent,
  demoteListIndent,
  unifyBulletMarkers,
  insertDocumentMap,
  selectInsideInlineMark,
  insertCheckboxStatsAtCursor,
  tagSectionLines,
  extractHtmlCommentsAsSection,
  insertSectionTaskProgressBar,
  foldAllCallouts,
  expandAllCallouts,
  ensureTimestampsInFrontmatter,
  surroundWithStyledMark,
  insertHrWith,
  cleanupAllWhitespace,
  linksToQrShortcut,
  extractTasksToSummarySection,
  promoteHeadingTree,
  demoteHeadingTree,
  insertTodayDailyWikilink,
  insertWeeklyWikilink,
  inlineFootnotesToReference,
  reorderTasksByStatus,
  explodeListToParagraphs,
  mergeAdjacentDuplicateHeadings,
  tableColumnToWikilinks,
  insertQuoteWithAttribution,
  wrapHeadingsAsBlockLinks,
  bulletsToOrdered,
  orderedToBullets,
  convertSelectionToFootnote,
  insertSectionDividerWithTitle,
  insertCurrentHeadingPermalink,
  insertWordCloudSnapshot,
  shuffleParagraphs,
  insertKbdSpan,
  sortFrontmatterArrayValues,
  insertMathEquationRef,
  sortH2SectionsByDate,
  insertSectionLastReviewedStamp,
  orderedToRoman,
  tasksToDefinitionList,
  insertCollapsibleTOC,
  redactSensitivePatterns,
  insertChecklistFromPromptedLines,
  splitCurrentHeading,
  mergeDuplicateWikilinks,
  linkPromptForSelection,
  blockquoteToCallout,
  calloutToBlockquote,
  paragraphsToSentenceBullets,
  emojifyHeadings,
  stripMarkdownToPlainCommand,
  insertTaskWithDeadline,
  annotateUrlsWithTitlePlaceholder,
  removeOrphanListMarkers,
  sortFrontmatterKeysAlpha,
  toggleLineStrikethrough,
  listToSingleColumnTable,
  mergeConsecutiveCodeBlocks,
  imagesToFigureCaption,
  sortH3InCurrentH2,
  expandInlineYamlObjects,
  insertRandomEpigraph,
  stampTaskDone,
  insertQuoteWithTag,
  wrapH3SectionsAsDetails,
  smartJoinSoftWraps,
  wikipediaUrlsToWikilinks,
  formatJsonCodeBlocks,
  formatYamlCodeBlocks,
  calloutsToAdmonition,
  insertColorSwatch,
  rot13Selection,
  insertRfc3339Timestamp,
  insertChecklistBarAtCursor,
  breakHeadingBeforeParagraph,
  wordWrapParagraphs,
  toggleSetextHeadings,
  orderedListToLettered,
  stripEmojiFromHeadings,
  surroundWithBrackets,
  insertEmDashHr,
  insertBacklinksPlaceholder,
  ensureCreatedUpdatedTimestamps,
  changeOrderedStart,
  wrapSelectionAsWikilinkSafe,
  tableToYamlObjects,
  insertMermaidSequence,
  stripWikilinkAliases,
  headingsToNestedList,
  normalizeMixedIndent,
  quoteSelectionLines,
  sortTableByColumnDesc,
  insertSectionWikilink,
  inlineCodeToWikilink,
  splitParagraphsBySentenceCount,
  reverseListBlock,
  wrapSpoiler,
  flipTableHeaderToFirstCol,
  boldNumericInHeadings,
  insertEmptyQuoteBlock,
  fillImageAltFromBasename,
  insertKbdShortcut,
  boldNumericToSup,
  insertFrontmatterField,
  insertMermaidFlowchart,
  insertMermaidGantt,
  insertMermaidClass,
  renameHierarchicalTag,
  listToTaskList,
  insertFrontmatterCallout,
  markAllTasksDone,
  escapeHtmlInCodeBlocks,
  ensureBlankBeforeHeadings,
  collapseBlankLines,
  insertMermaidPie,
  linkifyIssueRefs,
  insertKbdCheatsheet,
  boldToItalic,
  italicToBold,
  sortParagraphsByLength,
  reverseTableRows,
  tabsToSpacesInCode,
  insertCurrentH1Wikilink,
  removeEmptyHeadings,
  imagesToCaptionedBlock,
  insertDailyNoteRangeTable,
  expandWikilinkToAlias,
  dedupTaskLines,
  insertHintCallout,
  mp4LinkToVideoEmbed,
  reindentSpaceWidth,
  capitalizeSentencesAscii,
  unicodeArrows,
  inlineFootnotesV2,
  hideHeadingAsHtmlComment,
  insertYouTubeEmbed,
  orderedListToAsciiTree,
  doubleNewlineToBr,
  sortFrontmatterArrayField,
  insertNumberedChecklist,
  unwrapSoftLines,
  splitTableByRowCount,
  insertTasksByTagDataview,
  insertLastEditedLine,
  relativeMdLinksToWikilink,
  insertBibtexEntry,
  sortH2SectionsAlpha,
  setextToAtx,
  insertTagCloudSnapshot,
  dedupBulletList,
  renumberOrderedListsFromOne,
  insertAuthorDateHeader,
  togglePrivateComment,
  rewrapBlockquotes,
  promoteAllHeadings,
  demoteAllHeadings,
  insertIsoWeekHeading,
  orderedListToChecklist,
  checklistToOrdered,
  insertWikiRedirect,
  collapseDuplicateHeadings,
  wikilinkToFullMdLink,
  padFencedCodeBlocks,
  insertCustomHr,
  insertImageGalleryGrid,
  mergeAdjacentTables,
  sortFmKeysAlphaV2,
  insertPropertiesSummary,
  blockquoteToCalloutNote,
  priorityMarkersToWarning,
  stripWikilinks,
  insertMermaidMindmap,
  linkToFootnote,
  wrapParagraphsHtml,
  addHeadingStatusBadge,
  insertKatexBlock,
  orderedListToWikilinkList,
  insertWeeklyReviewTemplate,
  stripEmphasis,
  listToDefinitionList,
  wrapSelectionInQuoteCallout,
  insertRawHtmlSnippet,
  insertSidebarReference,
  appendTagToParagraphs,
  insertDocumentSubtitle,
  boldifyTags,
  asciiTasksToUnicode,
  insertSearchCallout,
  checkedTaskToEmoji,
  insertTocWithDepth,
  groupH3UnderH2Details,
  insertWikilinkAuditPlaceholder,
  insertTocWithTaskProgress,
  annotateHeadingsWithProgress,
  insertFrontmatterFromH1,
  tagsToWikilink,
  insertScrollTopButton,
  quoteCurrentParagraph,
  insertLast7DaysChain,
  asciiSymbolsToUnicode,
  copyCurrentSectionAsPlain,
  appendTableColumnStats,
  pinSectionToTop,
  listToOutliner,
  insertOgMetadataBlock,
  urlsToWikilink,
  insertCurrentMonthCalendar,
  sentencesPerLine,
  stripHtmlTags,
  insertHorizontalScrollContainer,
  insertExcelFormulaPlaceholder,
  archiveSectionToYear,
  emojiShortcodes,
  unifyBulletDash,
  tableColToWikilink,
  insertTilTemplate,
  dedupAdjacentParagraphsV2,
  insertPomodoroTracker,
  footnotesToInline,
  insertQuoteOfTheDay,
  insertReadingProfile,
  insertReverseOutline,
  insertMoodLogTable,
  checklistToDefinitionList,
  markLongParagraphs,
  boldifyRfcKeywords,
  frontmatterDatesToIso,
  renameTableColumn,
  sortTasksByPriorityEmoji,
  insertPrivacyNotice,
  appendTableTotalsRow,
  bubbleUncheckedTasksTop,
  insertRecurringTasksTemplate,
  stripAllMarkdown,
  listToMermaidPie,
  normalizeTableWhitespace,
  insertFaqQaBlock,
  swapParagraphs,
  insertTilRecentIndex,
  insertReadingLogTable,
  cycleCheckboxTriState,
  trimTrailingWhitespaceV2,
  sortFrontmatterBySpecOrder,
  insertWeeklyMeetingNotes,
  firstTableRowToList,
  insertTldrCallout,
  insertWeeklyHabitTracker,
  sortDateSectionsDesc,
  insertPageBreak,
  imagesToFigure,
  dedupFootnoteDefinitions,
  demoteH3ToH4,
  sortCalloutsByType,
  insertAttributedQuote,
  insertMermaidGanttV2,
  appendSourceToCurrentParagraph,
  collapseExtraBlankLines,
  insertNumberedFootnote,
  insertCurrentSectionAnchorLink,
  refLinksToInline,
  insertGlossaryTemplate,
  listToMermaidGraphLr,
  insertReviewSchedule,
  insertTemplaterVars,
  normalizeOrderedListStartAtOne,
  insertAdrTemplate,
  wrapSelectionAsKbd,
  insertHeadingMap,
  insertTocWithAnchors,
  sortH2SectionsByWordCountDesc,
  foldH2AsDetails,
  paragraphsToOrderedList,
  insertLiteratureNoteTemplate,
  insertDailyQuoteReflection,
  ddmmyyyyToIso,
  capitalizeHeadings,
  insertReadingProgressBar,
  smartQuotesToStraight,
  insertCodeSnippetTemplate,
  tagsToWikilinkInCurrentSection,
  insertLessonsLearnedTemplate,
  sortListByLengthDesc,
  insertSwotAnalysis,
  asterisksToUnderscores,
  underscoresToAsterisks,
  insertReleaseNotesTemplate,
  insertMocSkeleton,
  wikilinkImagesToMd,
  mdImagesToWikilink,
  insertStickyNoteCallout,
  insertSectionLineCountReport,
  insertSectionTocWikilinks,
  bulletListToBlockquote,
  insertAnniversaryTemplate,
  normalizeCalloutTypeCase,
  insertTodayIPlanTemplate,
  insertFootnoteCount,
  insertLicenseFooter,
  splitLongParagraphAtSentences,
  insertProsConsTable,
  insertHabitChainChecklist,
  blockquoteToParagraph,
  insertRiskRegister,
  sortTableByColumnAsc,
  insertDecisionLogRow,
  snakeCaseHeadingsToTitleCase,
  paragraphsToOrderedListReversed,
  insertOkrTemplate,
  unifyDashes,
  insertRaciMatrix,
  normalizeTaskListIndent,
  insertOneOnOneTemplate,
  nbspInDates,
  dedupConsecutiveBullets,
  insertEisenhowerMatrix,
  renumberOrderedListFrom,
  swapInlineLinkTextAndUrl,
  insertDailyGratitudeTemplate,
  insertRecurringExpenseTable,
  headingsToSentenceCase,
  normalizeWikilinkLowercase,
  insertPomodoroSessionLog,
  insertWeeklyReviewTemplateV2,
  orderedListToChecklistV2,
  indentTaskSubtree,
  insertReadingQueueTable,
  insertBugReportTemplate,
  capitalizeFirstWordPerSentence,
  sentenceToTitleCase,
  insertTldrAtTop,
  sortFrontmatterAliasesV2,
  insertJournalingPrompts,
  normalizeCalloutIndent,
  insertDesignDocTemplate,
  paragraphToNumberedFootnote,
  insertInvestingJournalEntry,
  insertCornellNotesLayout,
  insertApiEndpointTemplate,
  foldBulletSubitems,
  insertHabitTrackerMonthGrid,
  extractInlineUrls,
  insertMeetingAgendaTemplate,
  sortListByFirstEmoji,
  insertPostmortemTemplate,
  tableToCsvWithHeader,
  insertWeeklyHabitTableByISOWeek,
  selectionToSnakeCase,
  insertArchitectureSketchPlaceholder,
  removeBrokenInlineLinks,
  insertExperimentLogEntry,
  wrapBulletsInQuotes,
  insertReleaseChecklist,
  prefixAllBullets,
  lineNumbersAsComments,
  insertHabitsYesterdayTodayDiff,
  insertRfcTemplate,
  expandTabIndentToSpaces,
  replaceFirstHeadingWithFrontmatterTitle,
  insertDecisionTreeMermaid,
  insertMoodScalePicker,
  isoDatesToDotted,
  insertPremortemTemplate,
  selectionSnakeToCamelCase,
  insertSupportEscalationMatrix,
  reverseAdjacentBullets,
  insertTeamStandupTemplate,
  escapeMarkdownInSelection,
  insertBurndownPlaceholder,
  insertLinkedOutlineForSelection,
  dedupAdjacentIdenticalLines,
  insertOkrWeeklyCheckin,
  paragraphsToDashList,
  insertCostBenefitTable,
  slugifySelection,
  insertJournalWeeklySummary,
  setextToAtxHeadings,
  insertSprintRetroTemplate,
  paragraphsToMermaidMindmap,
  insertLinkedinPostOutline,
  commentOutSelection,
  insertReleaseArtifactChecklist,
  tasksToWikilinkInTasksSection,
  insertWeeklyMetricReview,
  sortSectionsByHeadingTitle,
  insertDecisionMatrix,
  splitSelectionToBulletsBySentences,
  insertListenedToTemplate,
  insertCustomerInterviewTemplate,
  insertFiveWhysTemplate,
  paragraphsToFishboneMermaid,
  normalizeBulletTrailingPunctuation,
  insertInfoboxTable,
  foldCalloutsToSummary,
  insertKanban4Cols,
  atxHeadingsToBoldParagraph,
  insertAsyncStandupTemplate,
  insertReadingSessionLog,
  insertDuplicateParagraphsReport,
  insertSbarTemplate,
  insertWeeklyExperimentReview,
  paragraphsToNumberedQa,
  capitalizeWikilinkTargets,
  insertSipocTable,
  insertLeanCoffeeAgenda,
  calloutTypeToAdmonitionKind,
  foldAllH2Sections,
  insertPrReviewChecklist,
  insertVocabFlashcardTable,
  insertHeadingsBookmarkReport,
  insertNpsSurveyLog,
  insertRiceTable,
  insertValueStreamMermaid,
  normalizeImageAltToFilename,
  insertDailyMoodSleep,
  paragraphsToDropdownSummary,
  insertCompetitorAnalysisMatrix,
  bulletsToGanttTimeline,
  capitalizeTaskDescriptions,
  insertTechDebtRegistry,
  insertReadingRoadmap,
  insertEventTimelineLog,
  insertGtdWeeklyReview,
  insertSpacedRepetitionSchedule,
  atxToSetextTopTwoLevels,
  insertCheckpointMarker,
  demoteFirstHeadingByOne,
  sortTableRowsByFirstColDesc,
  insertHypothesisTree,
  paragraphWordCountBadge,
  insertBacklogGroomingNotes,
  paragraphsToTwoColCallout,
  normalizeEmphasisInBullets,
  insertKpiDashboardTable,
  insertLabNotebookEntry,
  insertObjectivesSolutionTree,
  paragraphsToNumberedHeadings,
  insertWireframeAsciiPlaceholder,
  sentenceCaseBullets,
  insertRiskBurndownTable,
  tableRowsToWikilinks,
  insertDependencyGraphMermaid,
  insertWeeklyBookLog,
  prependBlockIdToLines,
  insertInventoryTable,
  insertWorkflowSwimlaneMermaid,
  insertAnkiFlashcardBlock,
  paragraphsToDefinitionList,
  insertOkrCheckIn,
  insertSupportRunbook,
  wrapSelectionInKeyboardTag,
  insertChangeManagementForm,
  paragraphsToOrderedListWithSubitems,
  capitalizeSectionTitles,
  insertReleaseTimeline,
  insertPomodoroDayLog,
  insertResearchFindingsTemplate,
  paragraphsToSummaryBlock,
  normalizeListSpacing,
  insertMocIndex,
  capitalizeAfterColonInHeadings,
  insertWeeklyStatusReport,
  replaceTabsInTablesWithPipes,
  insertDecisionJournalEntry,
  sortSectionsByDatePrefix,
  insertSprintPlanningTemplate,
  insertGlossaryEntry,
  paragraphsToAsciiBox,
  insertCodeStatsTable,
  paragraphsToLetterPrefixedList,
  insertProductHandoffTemplate,
  convertHeadingNumberingToRoman,
  insertWeeklyMetricsReport,
  smartIndentBulletByLevel,
  insertCustomerComplaintForm,
  paragraphsToTaskAssignedTable,
  insertReleaseAnnouncementTemplate,
  bracketAroundNumbersInBullets,
  insertBacklinksSummaryStub,
  paragraphsToHeatmapTable,
  insertDocumentFooter,
  insertUserInterviewKit,
  bulletsToFooterReferences,
  insertCodeReviewChecklistFull,
  paragraphsToCards,
  insertOnboardingPlan30_60_90,
  tableRowsToBulletPoints,
  insertPostmortemTimeline,
  uppercaseAcronymsInText,
  insertWeeklySnapshotChart,
  insertInterviewSessionLog,
  tagKanbanLanesByLabel,
  relabelCalloutType,
  countSentencesPerParagraph,
  insertCustomerLifeCycleTable,
  sentencesToOrderedList,
  insertDataModelSpec,
  tasksToBoardSwimlane,
  insertProjectCharter,
  moveImportantTasksToTop,
  insertWritingPromptCard,
  insertQuizFlashSheet,
  insertOperationsRunbook,
  mergeTablesByFirstColumn,
  insertInlineImageThumbnail,
  listDedupCaseInsensitive,
  insertGameJournalEntry,
  annotateLinksWithDomain,
  insertWorkoutSessionLog,
  paragraphsToReverseTimeline,
  insertCustomerJourneyTable,
  quoteRangeToBlockquote,
  insertWeeklyPlanningTemplate,
  paragraphsToFaqWithCount,
  numbersToSparkline,
  insertScrumBoardSnapshot,
  countTagOccurrences,
  normalizeHorizontalRulesToDashes,
  insertAdrShortForm,
  paragraphsToCalloutByLength,
  insertContentCalendarTable,
  stripWikilinkAlias,
  insertWelcomeReadme,
  listToBulletStar,
  insertBookSummaryTemplate,
  joinShortLines,
  insertFocusBlock90Min,
  insertBrainstormingMatrix,
  insertResearchPaperOutline,
  normalizeHashtagSpacing,
  insertRoadmapQuarters,
  trimTrailingPunctuationInHeadings,
  insertProductMetricsTree,
  lineRangeToCheckboxes,
  insertLearningPlanTemplate,
  paragraphsToCheatSheet,
  insertDeploymentChecklist,
  uppercaseFirstLetterPerLine,
  insertHealthDailyLog,
  insertThreatModelMatrix,
  insertHackathonPitchDeck,
  normalizeColonSpacing,
  insertOnePageProjectStatus,
  indentBlockquoteByOne,
  insertCustomerOnboardingFlow,
  paragraphsToFlashFiction,
  insertWritingPlatformStrategy,
  paragraphsToOneLinerSummaries,
  insertWeeklyRetrospectivePlus,
  reverseListOrder,
  insertKPIDashboard,
  insertSprintRetro4Ls,
  insertBookClubGuide,
  paragraphsToGlossaryIndex,
  normalizeTrailingWhitespace,
  insertWeeklyReviewTemplateV3,
  insertOrgChartMermaid,
  insertCodeReviewSummary,
  bulletsToPriorityMatrix,
  insertFeedbackSynthesis,
  insertIdeaToImpact,
  linesToQuoteCards,
  paragraphsToPullQuotes,
  insertOKRWorksheet,
  paragraphsToStudyCards,
  insertTechDebtLog,
  normalizeOrderedListToDashes,
  insertWeeklyContentPlan,
  insertLessonsLearnedLog,
  paragraphsToTLDRWithBullets,
  insertCustomerInterviewScript,
  bulletsToSWOTByEmoji,
  insertDecisionMatrixV2,
  linesReverseWithIndex,
  insertDailyStandupNotes,
  paragraphsToHeadlines,
  insertProductSpecTemplate,
  linesShuffle,
  insertSalesCallNotes,
  paragraphsToKeyTakeaways,
  insertGrantProposalOutline,
  bulletsByDayOfWeek,
  insertHiringScorecard,
  paragraphsToOnePager,
  insertTechnicalRFCTemplate,
  normalizeBlankLinesMax1,
  insertArchitectureContainerDiagram,
  paragraphsToActionRegister,
  insertPositioningTemplate,
  linesToTableWithIndex,
  insertVisionMissionValues,
  paragraphsToTalkOutline,
  tagStatsTop5,
  insertReleaseChecklistPlus,
  paragraphsToPodcastNotes,
  normalizeFenceLanguage,
  insertMindDiaryTemplate,
  joinLinesAsSentences,
  insertStrategyCanvas,
  paragraphsToStoryPitch,
  insertExperimentDesign,
  bulletsNestByDepthMarker,
  insertChurnAnalysis,
  paragraphsToFAQShort,
  insertSpeakingPrep,
  insertQuadrantChart,
  renumberOrderedList,
  insertOKRReviewSnapshot,
  paragraphsToMemo,
  wrapLinesInParens,
  insertJourneyMapTemplate,
  paragraphsToArgumentStructure,
  insertBrandVoiceGuide,
  bulletsToBingoCard,
  insertWeddingChecklist,
  paragraphsToAphorismCards,
  insertRecipeTemplate,
  linesToIndexedFAQ,
  normalizeBulletMarkerToDot,
  insertVacationItinerary,
  paragraphsToThesisStatement,
  stripDiacritics,
  insertKPITree,
  paragraphsToSalesPitch,
  insertSleepLogTemplate,
  bulletsToRadarChart,
  insertClassroomLessonPlan,
  paragraphsToStandupStatus,
  insertInvestorUpdate,
  linesToReadingList,
  paragraphsToTwitterThread,
  normalizeMarkdownLinksToRefStyle,
  insertGroceryList,
  headingsToTitleCase,
  insertADRTracker,
  paragraphsToMeetingSummary,
  insertUXResearchPlan,
  linesToHaiku,
  insertTournamentBracket,
  paragraphsToQuoteSandwich,
  insertAdventCalendar,
  bulletsToSwimLane,
  insertDailyMoodSnapshot,
  normalizeHeadingSpacing,
  paragraphsToFortuneCookies,
  headingsToNumberedTOCLinks,
  insertCapacityPlanningSheet,
  paragraphsToDemoScript,
  insertColorPaletteCard,
  linesToABCPriority,
  insertRetroStarfish,
  paragraphsToTestimonialWall,
  insertRunbookTemplatePlus,
  bulletsToCommitmentLadder,
  insertExecutiveSummaryTemplate,
  paragraphsToSoundbites,
  normalizeEmphasisMarkers,
  insertIncidentTimelineTemplate,
  insertReadingQueueTemplate,
  paragraphsToStickyNoteBoard,
  insertLinkRotScanTemplate,
  linesToParetoBar,
  insertMindmapOutlineTemplate,
  paragraphsToCustomerJourneyMoments,
  insertLabSafetyChecklist,
  bulletsToGitGraphMermaid,
  insertTrainingPlanCalendar,
  paragraphsToUserPersona,
  normalizeUnicodeWhitespace,
  insertProjectCharterTemplate,
  insertIncidentSeverityMatrix,
  paragraphsToExecutiveTalkingPoints,
  insertABTestScorecard,
  linesToTierList,
  insert306090DayPlan,
  paragraphsToPressRelease,
  insertDependencyMapMermaid,
  bulletsToChecklistSignedOff,
  insertSecurityAuditLogTemplate,
  paragraphsToKPITreeNarrative,
  normalizeOrderedListMarkers,
  insertDataMigrationRunbook,
  insertOrgStructureMermaidV2,
  paragraphsToFAQRichAnswers,
  insertCapacityVsDemandChart,
  linesToBalancedTreeAscii,
  insertRoleResponsibilityMatrix,
  paragraphsToMeetingAgendaFromTopics,
  insertDashboardLayoutTextGrid,
  bulletsToOutlineNumbered,
  insertCustomerFeedbackHeatmap,
  paragraphsToPressHeadlineCandidates,
  normalizeEmptyBulletItems,
  insertSprintDashboardTemplate,
} from './commands'

type PaletteCommand = {
  id: string
  label: string
  group: string
  shortcut?: string
  run: (view: EditorView) => void
}

/** Prompt strings live in module-level command closures, so use a fixed translator (no React hook here). */
const promptT = (key: string, fallback: string) =>
  i18next.getFixedT(null, 'document')(`command.palette.prompts.${key}`, { defaultValue: fallback })

const COMMANDS: PaletteCommand[] = [
  // Text
  { id: 'bold', group: 'Text', label: 'Bold', shortcut: '⌘B', run: (v) => { toggleBold(v) } },
  { id: 'italic', group: 'Text', label: 'Italic', shortcut: '⌘I', run: (v) => { toggleItalic(v) } },
  { id: 'strike', group: 'Text', label: 'Strikethrough', shortcut: '⌘⇧K', run: (v) => { toggleStrike(v) } },
  { id: 'code', group: 'Text', label: 'Inline Code', shortcut: '⌘E', run: (v) => { toggleInlineCode(v) } },
  { id: 'highlight', group: 'Text', label: 'Highlight', run: (v) => { insertHighlight()(v) } },
  { id: 'comment', group: 'Text', label: 'Comment', run: (v) => { insertComment()(v) } },

  // Heading
  { id: 'p', group: 'Heading', label: 'Body Text', shortcut: '⌘0', run: (v) => { setLineHeading(0)(v) } },
  { id: 'h1', group: 'Heading', label: 'Heading 1', shortcut: '⌘1', run: (v) => { setLineHeading(1)(v) } },
  { id: 'h2', group: 'Heading', label: 'Heading 2', shortcut: '⌘2', run: (v) => { setLineHeading(2)(v) } },
  { id: 'h3', group: 'Heading', label: 'Heading 3', shortcut: '⌘3', run: (v) => { setLineHeading(3)(v) } },
  { id: 'h4', group: 'Heading', label: 'Heading 4', shortcut: '⌘4', run: (v) => { setLineHeading(4)(v) } },
  { id: 'h5', group: 'Heading', label: 'Heading 5', shortcut: '⌘5', run: (v) => { setLineHeading(5)(v) } },
  { id: 'h6', group: 'Heading', label: 'Heading 6', shortcut: '⌘6', run: (v) => { setLineHeading(6)(v) } },

  // List
  { id: 'ul', group: 'List', label: 'Unordered List', shortcut: '⌘⇧8', run: (v) => { toggleBulletList(v) } },
  { id: 'ol', group: 'List', label: 'Ordered List', shortcut: '⌘⇧7', run: (v) => { toggleOrderedList(v) } },
  { id: 'todo', group: 'List', label: 'Todo', shortcut: '⌘⇧9', run: (v) => { toggleTodoList(v) } },
  { id: 'quote', group: 'List', label: 'Blockquote', shortcut: '⌘⇧.', run: (v) => { toggleQuote(v) } },
  { id: 'cycle-list', group: 'List', label: 'Cycle List Type (None → Unordered → Ordered → Todo)', shortcut: '⌘⇧L', run: (v) => { cycleListType(v) } },
  { id: 'demote-list-item', group: 'List', label: 'Indent List Item (with Sub-list)', run: (v) => { demoteListItem(v) } },
  { id: 'bullet-to-ordered', group: 'List', label: 'Unordered → Ordered List', run: (v) => { convertBulletListToOrdered(v) } },
  { id: 'ordered-to-bullet', group: 'List', label: 'Ordered → Unordered List', run: (v) => { convertOrderedListToBullet(v) } },

  // Insert blocks
  { id: 'mermaid', group: 'Insert', label: 'Mermaid Diagram', run: (v) => { insertCodeBlock('mermaid')(v) } },
  { id: 'table', group: 'Insert', label: 'Table 3×3', run: (v) => { insertTable(3, 3)(v) } },
  { id: 'table-add-col-right', group: 'Table', label: 'Insert Column Right', run: (v) => { tableAddColumnRight(v) } },
  { id: 'table-add-col-left', group: 'Table', label: 'Insert Column Left', run: (v) => { tableAddColumnLeft(v) } },
  { id: 'table-delete-col', group: 'Table', label: 'Delete Current Column', run: (v) => { tableDeleteColumn(v) } },
  { id: 'table-add-row-below', group: 'Table', label: 'Insert Row Below', run: (v) => { tableAddRowBelow(v) } },
  { id: 'table-add-row-above', group: 'Table', label: 'Insert Row Above', run: (v) => { tableAddRowAbove(v) } },
  { id: 'table-delete-row', group: 'Table', label: 'Delete Current Row', run: (v) => { tableDeleteRow(v) } },
  { id: 'table-align-left', group: 'Table', label: 'Current Column: Align Left', run: (v) => { tableAlignColumn('left')(v) } },
  { id: 'table-align-center', group: 'Table', label: 'Current Column: Align Center', run: (v) => { tableAlignColumn('center')(v) } },
  { id: 'table-align-right', group: 'Table', label: 'Current Column: Align Right', run: (v) => { tableAlignColumn('right')(v) } },
  { id: 'table-align-none', group: 'Table', label: 'Current Column: Clear Alignment', run: (v) => { tableAlignColumn('none')(v) } },
  { id: 'table-format', group: 'Table', label: 'Format Table (Align by Column Width)', run: (v) => { tableFormat(v) } },
  { id: 'table-transpose', group: 'Table', label: 'Transpose (Rows ↔ Columns)', run: (v) => { tableTranspose(v) } },
  { id: 'table-to-bullets', group: 'Table', label: 'Table → Bullet List (K: V)', run: (v) => { tableToBulletList(v) } },
  { id: 'bullets-to-table', group: 'Table', label: 'Bullet List → Table (`- a | b`)', run: (v) => { bulletListToTable(v) } },
  { id: 'table-sort-asc', group: 'Table', label: 'Sort by Current Column (Ascending)', run: (v) => { tableSortByColumn('asc')(v) } },
  { id: 'table-sort-desc', group: 'Table', label: 'Sort by Current Column (Descending)', run: (v) => { tableSortByColumn('desc')(v) } },
  { id: 'table-move-col-left', group: 'Table', label: 'Move Current Column Left', run: (v) => { tableMoveColumnLeft(v) } },
  { id: 'table-move-col-right', group: 'Table', label: 'Move Current Column Right', run: (v) => { tableMoveColumnRight(v) } },
  { id: 'table-move-row-up', group: 'Table', label: 'Move Current Row Up', run: (v) => { tableMoveRowUp(v) } },
  { id: 'table-move-row-down', group: 'Table', label: 'Move Current Row Down', run: (v) => { tableMoveRowDown(v) } },
  { id: 'hr', group: 'Insert', label: 'Horizontal Rule', run: (v) => { insertHorizontalRule()(v) } },
  { id: 'math-block', group: 'Insert', label: 'Math Block $$ … $$', run: (v) => { insertMathBlock()(v) } },
  { id: 'math', group: 'Insert', label: 'Inline Math $…$', run: (v) => { insertMath()(v) } },
  { id: 'callout-note', group: 'Insert', label: 'Callout (note)', run: (v) => { insertCallout('note')(v) } },
  { id: 'callout-tip', group: 'Insert', label: 'Callout (tip)', run: (v) => { insertCallout('tip')(v) } },
  { id: 'wrap-callout-note', group: 'Insert', label: 'Convert Selection/Line to Callout (note)', run: (v) => { convertSelectionToCallout('note')(v) } },
  { id: 'wrap-callout-tip', group: 'Insert', label: 'Convert Selection/Line to Callout (tip)', run: (v) => { convertSelectionToCallout('tip')(v) } },

  // Link
  { id: 'link', group: 'Link', label: 'Link [text](url)', shortcut: '⌘K', run: (v) => { insertLink()(v) } },
  { id: 'image', group: 'Link', label: 'Image ![alt](url)', run: (v) => { insertImage()(v) } },
  { id: 'wikilink', group: 'Link', label: 'Wikilink [[…]]', run: (v) => { insertWikilink()(v) } },
  { id: 'embed', group: 'Link', label: 'Embed ![[…]]', run: (v) => { insertEmbed()(v) } },
  { id: 'tag', group: 'Link', label: 'Tag #', run: (v) => { insertTag()(v) } },
  { id: 'footnote', group: 'Insert', label: 'Footnote [^N]', run: (v) => { insertFootnote(v) } },
  { id: 'footnote-jump', group: 'Navigation', label: 'Jump to Footnote ref ↔ def', shortcut: '⌘⌥F', run: (v) => { jumpFootnote(v) } },
  { id: 'heading-prev', group: 'Navigation', label: 'Previous Heading', shortcut: '⌘⌥↑', run: (v) => { jumpToPrevHeading(v) } },
  { id: 'heading-next', group: 'Navigation', label: 'Next Heading', shortcut: '⌘⌥↓', run: (v) => { jumpToNextHeading(v) } },
  { id: 'code-block-prev', group: 'Navigation', label: 'Previous Code Block', run: (v) => { jumpToPrevCodeBlock(v) } },
  { id: 'code-block-next', group: 'Navigation', label: 'Next Code Block', run: (v) => { jumpToNextCodeBlock(v) } },
  { id: 'task-prev', group: 'Navigation', label: 'Previous Task', run: (v) => { jumpToPrevTask(v) } },
  { id: 'task-next', group: 'Navigation', label: 'Next Task', run: (v) => { jumpToNextTask(v) } },
  { id: 'unwrap-link', group: 'Link', label: 'Unwrap Link (Keep Text)', run: (v) => { unwrapLink(v) } },
  { id: 'convert-link', group: 'Link', label: 'Toggle: wikilink ↔ Markdown Link', run: (v) => { convertLinkUnderCursor(v) } },

  // Navigation
  { id: 'search', group: 'Navigation', label: 'Search', shortcut: '⌘F', run: (v) => { openSearchPanel(v) } },
  { id: 'goto-line', group: 'Navigation', label: 'Go to Line', shortcut: '⌘⌥L', run: (v) => { gotoLine(v) } },

  // Heading promote/demote + task toggle
  { id: 'promote-heading', group: 'Heading', label: 'Promote Heading', shortcut: '⌘⇧[', run: (v) => { promoteHeading(v) } },
  { id: 'demote-heading', group: 'Heading', label: 'Demote Heading', shortcut: '⌘⇧]', run: (v) => { demoteHeading(v) } },
  { id: 'move-section-up', group: 'Heading', label: 'Move Section Up', run: (v) => { moveSectionUp(v) } },
  { id: 'move-section-down', group: 'Heading', label: 'Move Section Down', run: (v) => { moveSectionDown(v) } },
  { id: 'toggle-task', group: 'List', label: 'Toggle Task Checkbox', shortcut: '⌘↵', run: (v) => { toggleTaskCheckbox(v) } },

  // Tools
  { id: 'insert-date', group: 'Tools', label: 'Insert Date (YYYY-MM-DD)', run: (v) => { insertDate()(v) } },
  { id: 'insert-timestamp', group: 'Tools', label: 'Insert Timestamp (YYYY-MM-DD HH:mm)', run: (v) => { insertTimestamp()(v) } },
  { id: 'strip-frontmatter', group: 'Tools', label: 'Delete Frontmatter', run: (v) => { stripFrontmatter(v) } },
  { id: 'case-upper', group: 'Tools', label: 'Uppercase (Selection)', run: (v) => { transformCase('upper')(v) } },
  { id: 'case-lower', group: 'Tools', label: 'Lowercase (Selection)', run: (v) => { transformCase('lower')(v) } },
  { id: 'case-title', group: 'Tools', label: 'Title Case (Selection)', run: (v) => { transformCase('title')(v) } },
  { id: 'case-sentence', group: 'Tools', label: 'Sentence Case (Selection)', run: (v) => { transformCase('sentence')(v) } },
  { id: 'reverse-lines', group: 'Tools', label: 'Reverse Selected Lines', run: (v) => { reverseLines(v) } },
  { id: 'dedup-lines', group: 'Tools', label: 'Deduplicate Lines (Selection)', run: (v) => { dedupSelectedLines(v) } },
  { id: 'remove-empty-lines', group: 'Tools', label: 'Remove Empty Lines (Selection)', run: (v) => { removeEmptyLines(v) } },
  { id: 'sort-lines', group: 'Tools', label: 'Sort Selected Lines', run: (v) => { sortSelectedLines(v) } },
  { id: 'number-headings', group: 'Tools', label: 'Number All Headings (1.1.1)', run: (v) => { numberHeadings(v) } },
  { id: 'trim-ws', group: 'Tools', label: 'Trim Trailing Whitespace', run: (v) => { trimTrailingWhitespace(v) } },
  { id: 'smart-typography', group: 'Tools', label: 'Smart Typography (-- → — / ... → … / (c) → ©)', run: (v) => { applySmartTypography(v) } },
  { id: 'join-lines', group: 'Tools', label: 'Join Selection into One Line', run: (v) => { joinLines(v) } },
  { id: 'sort-tasks', group: 'Tools', label: 'Sort Tasks (Uncompleted First)', run: (v) => { sortTasks(v) } },
  { id: 'smart-arrows', group: 'Tools', label: 'Smart Arrows (-> → → / => → ⇒)', run: (v) => { applySmartArrows(v) } },
  { id: 'ensure-frontmatter', group: 'Tools', label: 'Insert Frontmatter Template', run: (v) => { ensureFrontmatter(v) } },
  { id: 'select-section', group: 'Tools', label: 'Select Current Section (Heading + Content)', shortcut: '⌘⇧A', run: (v) => { selectCurrentSection(v) } },
  { id: 'swap-line-up', group: 'Tools', label: 'Swap with Line Above', run: (v) => { swapLineUp(v) } },
  { id: 'swap-line-down', group: 'Tools', label: 'Swap with Line Below', run: (v) => { swapLineDown(v) } },
  { id: 'insert-uuid', group: 'Tools', label: 'Insert UUID v4', run: (v) => { insertUuid(v) } },
  { id: 'sort-frontmatter', group: 'Tools', label: 'Sort Frontmatter Fields (Alphabetically)', run: (v) => { sortFrontmatterKeys(v) } },
  { id: 'sort-fm-tags', group: 'Tools', label: 'Sort frontmatter.tags Values', run: (v) => { sortFrontmatterValues('tags')(v) } },
  { id: 'fold-current-section', group: 'Heading', label: 'Fold Current Section', run: (v) => { foldCurrentSection(v) } },
  { id: 'unfold-all', group: 'Heading', label: 'Expand All Folds', run: (v) => { unfoldAllSections(v) } },
  { id: 'selection-to-bullet', group: 'List', label: 'Selection → Bullet List', run: (v) => { selectionToBulletList(v) } },
  { id: 'selection-to-ol', group: 'List', label: 'Selection → Ordered List', run: (v) => { selectionToOrderedList(v) } },
  { id: 'selection-to-task', group: 'List', label: 'Selection → Task List', run: (v) => { selectionToTaskList(v) } },
  { id: 'paragraph-up', group: 'Paragraph', label: 'Move Paragraph Up', run: (v) => { swapAdjacentParagraphs('up')(v) } },
  { id: 'paragraph-down', group: 'Paragraph', label: 'Move Paragraph Down', run: (v) => { swapAdjacentParagraphs('down')(v) } },
  { id: 'ol-to-ul', group: 'List', label: 'Ordered List → Bullet', run: (v) => { convertOrderedToBullet(v) } },
  { id: 'ul-to-ol', group: 'List', label: 'Bullet → Ordered List', run: (v) => { convertBulletToOrdered(v) } },
  { id: 'links-to-ref', group: 'Link', label: 'Inline Links → Reference Style [n]', run: (v) => { expandShortLinksToReference(v) } },
  { id: 'links-to-inline', group: 'Link', label: 'Reference Links → Inline Style', run: (v) => { inlineReferenceLinks(v) } },
  { id: 'url-clean-tracking', group: 'Link', label: 'Strip URL Tracking Params (utm_/gclid)', run: (v) => { cleanTrackingParams(v) } },
  { id: 'setext-to-atx', group: 'Heading', label: 'Setext (===) → ATX (#)', run: (v) => { convertSetextHeadings(v) } },
  { id: 'atx-to-setext', group: 'Heading', label: 'ATX (#) → Setext (===) H1/H2', run: (v) => { convertAtxToSetext(v) } },
  { id: 'prune-empty-headings', group: 'Heading', label: 'Remove Empty Headings', run: (v) => { pruneEmptyHeadings(v) } },
  { id: 'join-sentences', group: 'Paragraph', label: 'Join Lines Within Paragraph (Remove Hard Breaks)', run: (v) => { joinSentences(v) } },
  { id: 'quote-s-to-d', group: 'Format', label: "Single Quotes → Double Quotes", run: (v) => { convertSingleQuoteToDouble(v) } },
  { id: 'quote-d-to-s', group: 'Format', label: "Double Quotes → Single Quotes", run: (v) => { convertDoubleQuoteToSingle(v) } },
  { id: 'wikilink-expand-alias', group: 'Link', label: 'Expand [[X]] → [[X|X]] Alias', run: (v) => { expandWikilinkAliases(v) } },
  { id: 'normalize-list-indent', group: 'List', label: 'Normalize List Indentation (4→2 Spaces)', run: (v) => { normalizeListIndentation(v) } },
  { id: 'escape-md', group: 'Format', label: 'Escape Markdown Special Characters', run: (v) => { escapeMarkdownInPlain(v) } },
  { id: 'unescape-md', group: 'Tools', label: 'Unescape Markdown Characters in Selection', run: (v) => { unescapeMarkdownSelection(v) } },
  { id: 'move-section-top', group: 'Heading', label: 'Move Current Section → Document Top', run: (v) => { moveSectionToTop(v) } },
  { id: 'move-section-bottom', group: 'Heading', label: 'Move Current Section → Document Bottom', run: (v) => { moveSectionToBottom(v) } },
  { id: 'toggle-inline-math', group: 'Insert', label: 'Toggle Inline Math $…$', run: (v) => { toggleInlineMath(v) } },
  { id: 'hard-wrap-80', group: 'Tools', label: 'Hard Wrap Paragraph (80 Columns)', run: (v) => { hardWrapSelection(80)(v) } },
  { id: 'unwrap-paragraphs', group: 'Tools', label: 'Unwrap Paragraphs (Merge Line Breaks)', run: (v) => { unwrapParagraphs(v) } },
  { id: 'sort-lines-desc', group: 'Tools', label: 'Sort Selected Lines (Descending)', run: (v) => { sortSelectedLinesDesc(v) } },
  { id: 'trim-section-blanks', group: 'Heading', label: 'Trim Blank Lines at Start/End of Section', run: (v) => { trimSectionBlanks(v) } },
  { id: 'images-to-wikilinks', group: 'Tools', label: 'Images: Markdown ![]() → Wikilink ![[]]', run: (v) => { convertImagesToWikilinks(v) } },
  { id: 'toggle-highlight', group: 'Format', label: 'Toggle Highlight ==…==', run: (v) => { toggleHighlight(v) } },
  { id: 'wrap-quote', group: 'Insert', label: 'Wrap Selection as Blockquote', run: (v) => { insertAsQuote(v) } },
  { id: 'wrap-code', group: 'Insert', label: 'Wrap Selection as Code Block', run: (v) => { wrapAsCodeBlock()(v) } },

  // Fold
  { id: 'fold-section', group: 'Fold', label: 'Fold Current Section', shortcut: '⌘⌥]', run: (v) => { foldCode(v) } },
  { id: 'unfold-section', group: 'Fold', label: 'Unfold Current Section', shortcut: '⌘⌥[', run: (v) => { unfoldCode(v) } },
  { id: 'fold-all', group: 'Fold', label: 'Fold All', run: (v) => { foldAll(v) } },
  { id: 'fold-to-h1', group: 'Fold', label: 'Show H1 Only (Fold H2 and Below)', shortcut: '⌘⌥1', run: (v) => { foldHeadingsBelowLevel(1)(v) } },
  { id: 'fold-to-h2', group: 'Fold', label: 'Show H1/H2 (Fold H3 and Below)', shortcut: '⌘⌥2', run: (v) => { foldHeadingsBelowLevel(2)(v) } },
  { id: 'fold-to-h3', group: 'Fold', label: 'Show H1–H3 (Fold H4 and Below)', shortcut: '⌘⌥3', run: (v) => { foldHeadingsBelowLevel(3)(v) } },

  // Slides
  { id: 'slide-break', group: 'Slides', label: 'Insert Slide Break (---)', run: (v) => { insertSlideBreak(v) } },
  { id: 'slide-next', group: 'Slides', label: 'Next Slide', run: (v) => { jumpToNextSlide(v) } },
  { id: 'slide-prev', group: 'Slides', label: 'Previous Slide', run: (v) => { jumpToPrevSlide(v) } },

  // Code block tools

  // Heading bulk operations

  // Plain text / CSV
  { id: 'copy-plain', group: 'Tools', label: 'Copy as Plain Text (Strip Markdown)', run: (v) => { copyAsPlainText(v) } },
  { id: 'table-to-csv', group: 'Table', label: 'Table → CSV (Selection, Comma)', run: (v) => { convertTableSelectionToCsv(',')(v) } },

  // Bulk task operations
  { id: 'mark-all-done', group: 'List', label: 'Mark All Tasks Done', run: (v) => { markAllTasks('done')(v) } },
  { id: 'mark-all-undone', group: 'List', label: 'Uncheck All Tasks', run: (v) => { markAllTasks('undone')(v) } },

  // OPML

  // Tag rename (prompts)
  {
    id: 'rename-tag',
    group: 'Tools',
    label: 'Rename Tag in Document…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const oldTag = window.prompt(promptT('oldTag', 'Old tag to replace (without #)'))
      if (!oldTag) return
      const newTag = window.prompt(promptT('newTag', 'New tag (without #)'), oldTag)
      if (!newTag) return
      renameDocumentTag(oldTag.trim(), newTag.trim())(v)
    },
  },

  // Preferences
  {
    id: 'toggle-spellcheck',
    group: 'Preferences',
    label: 'Toggle Spell Check',
    run: (v) => { setSpellcheck(v, !isSpellcheckOn(v)) },
  },

  // #141 timestamps / durations / ordered-list offset / bulk line prefix/suffix
  { id: 'insert-timestamp-datetime', group: 'Insert', label: 'Insert Current Date & Time', run: (v) => { insertTimestampAtCursor('datetime')(v) } },
  { id: 'insert-timestamp-iso', group: 'Insert', label: 'Insert Current ISO Timestamp', run: (v) => { insertTimestampAtCursor('iso')(v) } },
  { id: 'insert-timestamp-epoch', group: 'Insert', label: 'Insert Current Epoch (Seconds)', run: (v) => { insertTimestampAtCursor('epoch')(v) } },
  {
    id: 'prepend-each-line',
    group: 'Format',
    label: 'Prepend Prefix to Every Line…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const prefix = window.prompt(promptT('linePrefix', 'Prefix to add to start of each line (e.g. "> ")'))
      if (prefix == null) return
      prependLinesWith(prefix)(v)
    },
  },

  // #142
  { id: 'cycle-task-state', group: 'List', label: 'Cycle Task State (todo / doing / done / cancel / forwarded)', run: (v) => { cycleTaskStateAtCursor(v) } },
  { id: 'strip-highlights', group: 'Format', label: 'Remove All ==Highlight== Markers', run: (v) => { stripHighlights(v) } },
  { id: 'strip-bold', group: 'Format', label: 'Remove All **Bold** Markers', run: (v) => { stripBold(v) } },
  { id: 'strip-italic', group: 'Format', label: 'Remove All *Italic* / _Italic_ Markers', run: (v) => { stripItalic(v) } },
  { id: 'stamp-updated-frontmatter', group: 'Frontmatter', label: 'Stamp frontmatter.updated = Today', run: (v) => { stampUpdatedFrontmatter(v) } },

  // #143
  { id: 'sort-frontmatter-aliases', group: 'Frontmatter', label: 'Sort aliases Field', run: (v) => { sortFrontmatterAliases(v) } },
  { id: 'blockquote-lines', group: 'Format', label: 'Add > to Every Line (blockquote)', run: (v) => { blockquoteLines(v) } },
  { id: 'unblockquote-lines', group: 'Format', label: 'Remove One > from Every Line', run: (v) => { unblockquoteLines(v) } },

  // #144
  { id: 'callout-to-note', group: 'Insert', label: 'Change Current Callout → note', run: (v) => { changeCalloutTypeAtCursor('note')(v) } },
  { id: 'callout-to-warning', group: 'Insert', label: 'Change Current Callout → warning', run: (v) => { changeCalloutTypeAtCursor('warning')(v) } },
  {
    id: 'kanban-add-column',
    group: 'Kanban',
    label: 'New Kanban Column…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const name = window.prompt(promptT('columnName', 'Column name'))
      if (!name) return
      insertKanbanColumn(name.trim())(v)
    },
  },
  {
    id: 'kanban-add-card',
    group: 'Kanban',
    label: 'Append Kanban Card to Current Column…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const text = window.prompt(promptT('cardContent', 'Card content'))
      if (!text) return
      insertKanbanCard(text.trim())(v)
    },
  },
  {
    id: 'rename-inline-dataview',
    group: 'Tools',
    label: 'Rename Dataview Inline Field…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const oldKey = window.prompt(promptT('oldFieldName', 'Old field name (without ::)'))
      if (!oldKey) return
      const newKey = window.prompt(promptT('newFieldName', 'New field name (without ::)'), oldKey)
      if (!newKey) return
      renameInlineDataviewField(oldKey.trim(), newKey.trim())(v)
    },
  },
  { id: 'swap-line-next', group: 'Line', label: 'Swap Current Line with Next Line', run: (v) => { swapWithNextLine(v) } },
  { id: 'swap-line-prev', group: 'Line', label: 'Swap Current Line with Previous Line', run: (v) => { swapWithPrevLine(v) } },
  { id: 'strip-html-comments', group: 'Format', label: 'Remove All <!-- HTML Comments -->', run: (v) => { stripHtmlComments(v) } },

  // #145
  { id: 'extract-wikilink-line', group: 'Wikilink', label: 'Extract Current Wikilink to Its Own Line', run: (v) => { extractWikilinkToOwnLine(v) } },
  {
    id: 'insert-titled-divider',
    group: 'Insert',
    label: 'Insert Titled Divider…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const t = window.prompt(promptT('dividerTitle', 'Divider title'))
      if (!t) return
      insertTitledDivider(t.trim())(v)
    },
  },
  {
    id: 'fm-inline-to-block',
    group: 'Frontmatter',
    label: 'Frontmatter Field: Inline Array → Block Form…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const key = window.prompt(promptT('frontmatterFieldName', 'Field name (e.g. tags)'))
      if (!key) return
      frontmatterFieldInlineToBlock(key.trim())(v)
    },
  },
  {
    id: 'fm-block-to-inline',
    group: 'Frontmatter',
    label: 'Frontmatter Field: Block → Inline Array…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const key = window.prompt(promptT('frontmatterFieldName', 'Field name (e.g. tags)'))
      if (!key) return
      frontmatterFieldBlockToInline(key.trim())(v)
    },
  },
  { id: 'swap-wikilink-alias', group: 'Wikilink', label: 'Swap Current Wikilink Alias and Target', run: (v) => { swapWikilinkAliasAndTargetAtCursor(v) } },
  {
    id: 'stamp-lines-date',
    group: 'Tools',
    label: 'Stamp Lines with Date…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const d = window.prompt(promptT('date', 'Date (YYYY-MM-DD)'), new Date().toISOString().slice(0, 10))
      if (!d) return
      stampLinesWithDate(d.trim())(v)
    },
  },

  // #146 lint
  { id: 'lint-fix-all', group: 'Lint', label: 'Markdown Lint: Fix All Common Issues', run: (v) => { fixCommonMarkdownLints(v) } },
  { id: 'lint-collapse-blanks', group: 'Lint', label: 'Collapse Excessive Blank Lines (≤2)', run: (v) => { collapseExcessiveBlankLines(v) } },
  { id: 'lint-list-space', group: 'Lint', label: 'Single Space After List Marker', run: (v) => { singleSpaceAfterListMarker(v) } },
  { id: 'lint-heading-space', group: 'Lint', label: 'Ensure Blank Lines Around Headings', run: (v) => { ensureBlankAroundHeadings(v) } },
  { id: 'lint-trailing-eol', group: 'Lint', label: 'Ensure Single Trailing Newline', run: (v) => { ensureSingleTrailingNewline(v) } },
  { id: 'lint-trim-trailing', group: 'Lint', label: 'Trim Trailing Whitespace (Keep Soft Breaks)', run: (v) => { trimTrailingNonBreakWhitespace(v) } },
  { id: 'lint-sort-fm-keys', group: 'Lint', label: 'Sort Frontmatter Top-Level Keys Alphabetically', run: (v) => { sortFrontmatterTopKeys(v) } },
  { id: 'lint-emphasis-star', group: 'Lint', label: 'Normalize Emphasis to *italic*', run: (v) => { normalizeEmphasisToAsterisk(v) } },
  { id: 'lint-strong-star', group: 'Lint', label: 'Normalize Strong to **bold**', run: (v) => { normalizeStrongToAsterisk(v) } },

  // #147
  {
    id: 'split-section-at-cursor',
    group: 'Heading',
    label: 'Split Section at Cursor (Same-Level Heading)…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const t = window.prompt(promptT('newSectionHeading', 'New section heading'))
      if (!t) return
      splitSectionAtCursor(t.trim())(v)
    },
  },
  { id: 'indent-2', group: 'List', label: 'Indent Selection by 2 Spaces', run: (v) => { indentLinesBySpaces(2)(v) } },
  { id: 'dedent-2', group: 'List', label: 'Dedent Selection by 2 Spaces', run: (v) => { dedentLinesBySpaces(2)(v) } },
  { id: 'plain-url-to-autolink', group: 'Link', label: 'Convert Bare URLs to <autolink>', run: (v) => { plainUrlToAutolink(v) } },
  {
    id: 'fm-template-default',
    group: 'Frontmatter',
    label: 'Apply Default Frontmatter Template',
    run: (v) => {
      applyFrontmatterTemplate({
        title: '',
        date: new Date().toISOString().slice(0, 10),
        tags: '[]',
        status: 'draft',
      })(v)
    },
  },
  { id: 'shift-headings-down-one', group: 'Heading', label: 'Demote All Headings by One Level', run: (v) => { shiftHeadingsDownOneLevel(v) } },

  // #148
  { id: 'links-to-footnotes', group: 'Link', label: 'Convert All [text](url) to Footnotes', run: (v) => { convertLinksToFootnotes(v) } },
  {
    id: 'surround-line-with-tag',
    group: 'Format',
    label: 'Wrap Each Line in HTML Tag…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const t = window.prompt(promptT('htmlTagName', 'HTML tag name (e.g. p / em / strong)'))
      if (!t) return
      surroundEachLineWithTag(t.trim())(v)
    },
  },
  { id: 'callouts-to-headings', group: 'Format', label: 'All Callouts → ## Headings', run: (v) => { calloutsToHeadings(v) } },

  // #149
  { id: 'insert-flashcard-separator', group: 'Review', label: 'Insert :: Separator at Cursor', run: (v) => { insertFlashcardSeparator(v) } },
  { id: 'lowercase-all-tags', group: 'Tools', label: 'Lowercase All #TAGS', run: (v) => { lowercaseAllTags(v) } },

  // #150
  { id: 'image-md-to-wiki-embed', group: 'Image', label: 'All Images → ![[embed]]', run: (v) => { convertMarkdownImagesToWikiEmbeds(v) } },
  {
    id: 'image-width-custom',
    group: 'Image',
    label: 'Set All ![[image]] Custom Width…',
    run: (v) => {
      if (typeof window === 'undefined' || typeof window.prompt !== 'function') return
      const w = window.prompt(promptT('widthInPixels', 'Width in pixels'), '400')
      if (!w) return
      const n = parseInt(w, 10)
      if (!Number.isFinite(n) || n <= 0) return
      setImageWidthForEmbeds(n)(v)
    },
  },
  { id: 'mdlink-to-wikilink', group: 'Link', label: 'Relative [text](path) → [[wiki]]', run: (v) => { relativeMdLinksToWikilinks(v) } },
  { id: 'fill-image-alt-from-filename', group: 'Image', label: 'Fill Image Alt from Full Filename', run: (v) => { fillImageAltFromFilename(v) } },
  { id: 'wrap-as-autodetected-code', group: 'Insert', label: 'Wrap Selection as Fenced Code (Auto-detect Lang)', run: (v) => { wrapSelectionAsAutodetectedCode(v) } },
  { id: 'highlights-to-mark', group: 'Format', label: '==Highlight== → <mark>', run: (v) => { highlightsToMark(v) } },
  { id: 'normalize-bullets-dash', group: 'List', label: 'Normalize Bullet Markers to - (Entire Document)', run: (v) => { normalizeBulletsToDash(v) } },
  { id: 'insert-note-metadata', group: 'Frontmatter', label: 'Insert Metadata Template at Top', run: (v) => { insertNoteMetadataBlock(v) } },
  { id: 'table-empty-row', group: 'Table', label: 'Append Empty Row to Table', run: (v) => { insertTableEmptyRow(v) } },
  { id: 'annotate-wikilinks-star', group: 'Wikilink', label: 'Annotate Wikilinks with ✨', run: (v) => { annotateWikilinksWithEmoji('✨')(v) } },
  { id: 'promote-h1-to-fm', group: 'Frontmatter', label: 'H1 → frontmatter title', run: (v) => { promoteH1ToFrontmatterTitle(v) } },
  { id: 'align-images-center', group: 'Image', label: 'Center Images', run: (v) => { alignImages('center')(v) } },
  { id: 'align-images-right', group: 'Image', label: 'Right-Align Images', run: (v) => { alignImages('right')(v) } },
  { id: 'rename-wikilink-prompt', group: 'Wikilink', label: 'Rename Wikilink Target…', run: (v) => {
    const o = window.prompt(promptT('originalWikilink', 'Original wikilink name (e.g. OldName):'))
    if (!o) return
    const n = window.prompt(promptT('newWikilink', 'New wikilink name (e.g. NewName):'))
    if (!n) return
    renameWikilinkInDoc(o, n)(v)
  } },
  { id: 'tags-to-wikilinks', group: 'Wikilink', label: '#tag → [[tag]]', run: (v) => { tagsToWikilinks(v) } },
  { id: 'toggle-callout-fold', group: 'Format', label: 'Toggle Callout Fold State (/ + / -)', run: (v) => { toggleCalloutFold(v) } },
  { id: 'sort-lines-by-length-asc', group: 'Line', label: 'Sort Lines by Length (Ascending)', run: (v) => { sortLinesByLengthAsc(v) } },
  { id: 'sort-lines-by-length-desc', group: 'Line', label: 'Sort Lines by Length (Descending)', run: (v) => { sortLinesByLengthDesc(v) } },
  { id: 'obs-embed-to-md-images', group: 'Image', label: '![[wikilink]] Embed → Markdown Images', run: (v) => { documentEmbedToMdImages(v) } },
  { id: 'expand-callout-aliases', group: 'Format', label: 'Expand Callout Aliases (i/w/e/…)', run: (v) => { expandCalloutAliases(v) } },
  { id: 'outline-keep-h1', group: 'Outline', label: 'Filter Outline: Keep H1 Only', run: (v) => { filterOutlineByLevel(1)(v) } },
  { id: 'outline-keep-h2', group: 'Outline', label: 'Filter Outline: Keep H1 + H2', run: (v) => { filterOutlineByLevel(2)(v) } },
  { id: 'outline-keep-h3', group: 'Outline', label: 'Filter Outline: Keep H1 + H2 + H3', run: (v) => { filterOutlineByLevel(3)(v) } },
  { id: 'autolink-bare-urls', group: 'Link', label: 'Bare URLs → [host](url) Autolinks', run: (v) => { autoLinkBareUrls(v) } },
  { id: 'split-paragraph-at-cursor', group: 'Line', label: 'Split Paragraph at Cursor into Two', run: (v) => { splitParagraphAtCursor(v) } },
  { id: 'jump-next-wikilink', group: 'Navigation', label: 'Jump to Next Wikilink', run: (v) => { jumpToNextWikilink(v) } },
  { id: 'jump-prev-wikilink', group: 'Navigation', label: 'Jump to Previous Wikilink', run: (v) => { jumpToPrevWikilink(v) } },
  { id: 'insert-document-map', group: 'Insert', label: 'Insert Document Map at Bottom (H1–H3)', run: (v) => { insertDocumentMap(v) } },
  { id: 'insert-hr-dash', group: 'Insert', label: 'Insert Divider ---', run: (v) => { insertHrWith('---')(v) } },
  { id: 'cleanup-all-whitespace', group: 'Tools', label: 'Clean Up BOM/Zero-Width/Tab/Trailing Whitespace', run: (v) => { cleanupAllWhitespace(v) } },
  { id: 'promote-heading-tree', group: 'Heading', label: 'Promote Current Section Heading Tree', run: (v) => { promoteHeadingTree(v) } },
  { id: 'demote-heading-tree', group: 'Heading', label: 'Demote Current Section Heading Tree', run: (v) => { demoteHeadingTree(v) } },
  { id: 'insert-kbd', group: 'Insert', label: 'Insert <kbd> Key…', run: (v) => {
    const k = window.prompt(promptT('kbdKey', 'Key (e.g. Ctrl+K):')) ?? 'Ctrl+K'
    insertKbdSpan(k)(v)
  } },
  { id: 'sort-frontmatter-arrays', group: 'Frontmatter', label: 'Sort All Inline Array Fields', run: (v) => { sortFrontmatterArrayValues(v) } },
  { id: 'link-prompt-selection', group: 'Link', label: '⌘K-style Link Prompt…', run: (v) => { linkPromptForSelection(v) } },
  { id: 'blockquote-to-callout-note', group: 'Format', label: 'blockquote → callout (note)', run: (v) => { blockquoteToCallout('note')(v) } },
  { id: 'callout-to-blockquote', group: 'Format', label: 'callout → Plain Blockquote', run: (v) => { calloutToBlockquote(v) } },
  { id: 'strip-markdown-to-plain', group: 'Tools', label: 'Strip Markdown to Plain Text', run: (v) => { stripMarkdownToPlainCommand(v) } },
  { id: 'sort-frontmatter-keys', group: 'Frontmatter', label: 'Sort Frontmatter Keys Alphabetically', run: (v) => { sortFrontmatterKeysAlpha(v) } },
  { id: 'stamp-task-done', group: 'Tools', label: 'Stamp Current Task ✓ Done Timestamp', run: (v) => { stampTaskDone(v) } },
  { id: 'insert-rfc3339', group: 'Insert', label: 'Insert RFC-3339 Timestamp', run: (v) => { insertRfc3339Timestamp(v) } },
  { id: 'word-wrap-80', group: 'Format', label: 'Hard-Wrap Paragraphs at 80 Columns', run: (v) => { wordWrapParagraphs(80)(v) } },
  { id: 'word-wrap-100', group: 'Format', label: 'Hard-Wrap Paragraphs at 100 Columns', run: (v) => { wordWrapParagraphs(100)(v) } },
  { id: 'insert-emdash-hr', group: 'Insert', label: 'Insert Em-Dash Divider ———', run: (v) => { insertEmDashHr(v) } },
  { id: 'fm-timestamps', group: 'Frontmatter', label: 'Add / Refresh created/updated Timestamps', run: (v) => { ensureCreatedUpdatedTimestamps(v) } },
  { id: 'insert-mermaid-seq', group: 'Insert', label: 'Insert Mermaid Sequence Diagram Skeleton', run: (v) => { insertMermaidSequence(v) } },
  { id: 'insert-section-wikilink', group: 'Link', label: 'Insert [[file#section]]…', run: (v) => { insertSectionWikilink(v) } },
  { id: 'inline-code-to-wikilink', group: 'Wikilink', label: '`code` → [[wikilink]]', run: (v) => { inlineCodeToWikilink(v) } },
  { id: 'fm-insert-tags', group: 'Frontmatter', label: 'Insert Frontmatter Field…', run: (v) => {
    const key = window.prompt(promptT('fieldName', 'Field name:'), 'tags')?.trim()
    if (!key) return
    const value = window.prompt(promptT('fieldValue', 'Value:'), '[]')?.trim() ?? ''
    insertFrontmatterField(key, value)(v)
  } },
  { id: 'insert-mermaid-flow', group: 'Insert', label: 'Insert Mermaid Flowchart Skeleton', run: (v) => { insertMermaidFlowchart(v) } },
  { id: 'insert-mermaid-gantt', group: 'Insert', label: 'Insert Mermaid Gantt Skeleton', run: (v) => { insertMermaidGantt(v) } },
  { id: 'insert-mermaid-class', group: 'Insert', label: 'Insert Mermaid Class Diagram Skeleton', run: (v) => { insertMermaidClass(v) } },
  { id: 'list-to-task-list', group: 'List', label: 'List → Task List - [ ]', run: (v) => { listToTaskList(v) } },
  { id: 'ensure-blank-before-heading', group: 'Lint', label: 'Ensure Blank Line Before Headings', run: (v) => { ensureBlankBeforeHeadings(v) } },
  { id: 'insert-mermaid-pie', group: 'Insert', label: 'Insert Mermaid Pie Chart', run: (v) => { insertMermaidPie(v) } },
  { id: 'bold-to-italic', group: 'Format', label: 'All **Bold** → *Italic*', run: (v) => { boldToItalic(v) } },
  { id: 'italic-to-bold', group: 'Format', label: 'All *Italic* → **Bold**', run: (v) => { italicToBold(v) } },
  { id: 'expand-wikilink-alias', group: 'Wikilink', label: '[[X]] → [[X|X]]', run: (v) => { expandWikilinkToAlias(v) } },
  { id: 'toggle-private-comment', group: 'Format', label: 'Toggle %%…%% Private Comment on Selection', run: (v) => { togglePrivateComment(v) } },
  { id: 'ordered-to-checklist', group: 'List', label: 'Ordered List → Task List', run: (v) => { orderedListToChecklist(v) } },
  { id: 'checklist-to-ordered', group: 'List', label: 'Task List → Ordered List', run: (v) => { checklistToOrdered(v) } },
  { id: 'strip-wikilinks', group: 'Link', label: 'Strip All Wikilinks (Keep Text)', run: (v) => { stripWikilinks(v) } },
  { id: 'insert-mermaid-mindmap', group: 'Insert', label: 'Insert Mermaid Mindmap', run: (v) => { insertMermaidMindmap(v) } },
  { id: 'insert-katex-block', group: 'Insert', label: 'Insert KaTeX Block', run: (v) => { insertKatexBlock(v) } },
  { id: 'strip-emphasis', group: 'Format', label: 'Strip All **/* Emphasis', run: (v) => { stripEmphasis(v) } },
  { id: 'insert-raw-html', group: 'Insert', label: 'Insert Raw HTML Snippet…', run: (v) => {
    const h = window.prompt(promptT('htmlSnippet', 'HTML snippet:'), '<details>\n<summary>title</summary>\nbody\n</details>')
    if (!h) return
    insertRawHtmlSnippet(h)(v)
  } },
  { id: 'boldify-tags', group: 'Tag', label: 'Bold All #tags', run: (v) => { boldifyTags(v) } },
  { id: 'insert-fm-from-h1', group: 'Frontmatter', label: 'Generate Frontmatter from H1', run: (v) => { insertFrontmatterFromH1(v) } },
  { id: 'tags-to-wikilink', group: 'Tag', label: '#tag → [[tag]]', run: (v) => { tagsToWikilink(v) } },
  { id: 'strip-html-tags', group: 'Format', label: 'Strip All HTML Tags', run: (v) => { stripHtmlTags(v) } },
  { id: 'fm-dates-to-iso', group: 'Frontmatter', label: 'Frontmatter Dates → ISO YYYY-MM-DD', run: (v) => { frontmatterDatesToIso(v) } },
  { id: 'strip-all-markdown', group: 'Format', label: 'Strip All Markdown Formatting (Plain Text)', run: (v) => { stripAllMarkdown(v) } },
  { id: 'normalize-table-ws', group: 'Table', label: 'Normalize Table Cell Whitespace', run: (v) => { normalizeTableWhitespace(v) } },
  { id: 'trim-trailing-ws-v2', group: 'Format', label: 'Trim Trailing Whitespace', run: (v) => { trimTrailingWhitespaceV2(v) } },
  { id: 'insert-tldr', group: 'Insert', label: 'Insert TL;DR Summary Callout', run: (v) => { insertTldrCallout(v) } },
  { id: 'insert-page-break', group: 'Insert', label: 'Insert Page Break (HTML)', run: (v) => { insertPageBreak(v) } },
  { id: 'insert-current-section-anchor', group: 'Link', label: 'Insert Current Section [[#anchor]]', run: (v) => { insertCurrentSectionAnchorLink(v) } },
  { id: 'insert-toc-anchors', group: 'Insert', label: 'Insert TOC with #anchor Links', run: (v) => { insertTocWithAnchors(v) } },
  { id: 'smart-quotes-to-straight', group: 'Format', label: 'Smart Quotes → Straight Quotes', run: (v) => { smartQuotesToStraight(v) } },
  { id: 'asterisks-to-underscores', group: 'Format', label: 'Emphasis `*` → `_`', run: (v) => { asterisksToUnderscores(v) } },
  { id: 'underscores-to-asterisks', group: 'Format', label: 'Emphasis `_` → `*`', run: (v) => { underscoresToAsterisks(v) } },
  { id: 'insert-section-toc-wikilinks', group: 'Navigation', label: 'Insert Section TOC (Wikilink)', run: (v) => { insertSectionTocWikilinks(v) } },
  { id: 'bullet-to-blockquote', group: 'Format', label: 'Unordered List → Blockquote', run: (v) => { bulletListToBlockquote(v) } },
  { id: 'normalize-callout-case', group: 'Lint', label: 'Normalize Callout Type to Lowercase', run: (v) => { normalizeCalloutTypeCase(v) } },
  { id: 'blockquote-to-paragraph', group: 'Format', label: 'Blockquote → Paragraph', run: (v) => { blockquoteToParagraph(v) } },
  { id: 'unify-dashes', group: 'Format', label: '`--` → Em-Dash', run: (v) => { unifyDashes(v) } },
  { id: 'normalize-task-indent', group: 'Lint', label: 'Normalize Task List Indentation', run: (v) => { normalizeTaskListIndent(v) } },
  { id: 'wikilink-lowercase', group: 'Wikilink', label: 'Wikilink Target → Lowercase', run: (v) => { normalizeWikilinkLowercase(v) } },
  { id: 'normalize-callout-indent', group: 'Lint', label: 'Normalize Callout Indentation', run: (v) => { normalizeCalloutIndent(v) } },
  { id: 'comment-out-selection', group: 'Format', label: 'Comment Out Selection (HTML)', run: (v) => { commentOutSelection(v) } },
  { id: 'sort-sections-by-title', group: 'Navigation', label: 'Sort H2 Sections by Title', run: (v) => { sortSectionsByHeadingTitle(v) } },
  { id: 'capitalize-wikilink-targets', group: 'Wikilink', label: 'Capitalize Wikilink Target First Letter', run: (v) => { capitalizeWikilinkTargets(v) } },
  { id: 'normalize-image-alt', group: 'Lint', label: 'Fill Image Alt from Filename', run: (v) => { normalizeImageAltToFilename(v) } },
  { id: 'normalize-bullet-emphasis', group: 'Lint', label: 'Normalize Bullet Emphasis Markers', run: (v) => { normalizeEmphasisInBullets(v) } },
  { id: 'normalize-list-spacing', group: 'Lint', label: 'Clean Up Extra Blank Lines in Lists', run: (v) => { normalizeListSpacing(v) } },
  { id: 'normalize-horizontal-rules', group: 'Lint', label: 'Normalize Horizontal Rules to ---', run: (v) => { normalizeHorizontalRulesToDashes(v) } },
  { id: 'normalize-hashtag-spacing', group: 'Lint', label: 'Add Space Before Tags', run: (v) => { normalizeHashtagSpacing(v) } },
  { id: 'normalize-trailing-ws', group: 'Lint', label: 'Normalize Trailing Whitespace', run: (v) => { normalizeTrailingWhitespace(v) } },
  { id: 'normalize-blank-lines-max1', group: 'Lint', label: 'Limit Blank Lines to Max 1', run: (v) => { normalizeBlankLinesMax1(v) } },
  { id: 'normalize-fence-language', group: 'Lint', label: 'Normalize Empty Fence Language → txt', run: (v) => { normalizeFenceLanguage(v) } },
  { id: 'renumber-ordered-list', group: 'Lint', label: 'Renumber Ordered List', run: (v) => { renumberOrderedList(v) } },
  { id: 'normalize-heading-spacing', group: 'Lint', label: 'Normalize Heading Spacing', run: (v) => { normalizeHeadingSpacing(v) } },
  { id: 'normalize-emphasis-markers', group: 'Lint', label: 'Normalize Emphasis Markers _ → *', run: (v) => { normalizeEmphasisMarkers(v) } },
  { id: 'normalize-unicode-whitespace', group: 'Lint', label: 'Normalize Unicode Whitespace', run: (v) => { normalizeUnicodeWhitespace(v) } },
  { id: 'normalize-ordered-list-markers', group: 'Lint', label: 'Normalize Ordered List Markers 1) → 1.', run: (v) => { normalizeOrderedListMarkers(v) } },
]

export type PaletteExtra = {
  id: string
  group: string
  label: string
  shortcut?: string
  run: () => void
}

export type CommandPaletteProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  getView: () => EditorView | null
  /** Extra commands injected by the host (context-sensitive, e.g. toggle current file favorite, copy path, etc.) */
  extras?: PaletteExtra[]
}

export function DocumentCommandPalette({ open, onOpenChange, getView, extras }: CommandPaletteProps) {
  const { t } = useTranslation('document')
  const [query, setQuery] = useState('')

  useEffect(() => {
    if (!open) setQuery('')
  }, [open])

  const groups = useMemo(() => {
    const byGroup = new Map<string, PaletteCommand[]>()
    for (const cmd of COMMANDS) {
      const arr = byGroup.get(cmd.group) ?? []
      arr.push(cmd)
      byGroup.set(cmd.group, arr)
    }
    return Array.from(byGroup.entries())
  }, [])

  const extraGroups = useMemo(() => {
    if (!extras || extras.length === 0) return []
    const byGroup = new Map<string, PaletteExtra[]>()
    for (const cmd of extras) {
      const arr = byGroup.get(cmd.group) ?? []
      arr.push(cmd)
      byGroup.set(cmd.group, arr)
    }
    return Array.from(byGroup.entries())
  }, [extras])

  const execute = (cmd: PaletteCommand) => {
    onOpenChange(false)
    const view = getView()
    if (!view) return
    // close the palette, then focus back to editor
    queueMicrotask(() => {
      cmd.run(view)
      view.focus()
    })
  }

  const executeExtra = (cmd: PaletteExtra) => {
    onOpenChange(false)
    queueMicrotask(() => {
      cmd.run()
      getView()?.focus()
    })
  }

  return (
    <CommandDialog open={open} onOpenChange={onOpenChange}>
      <CommandInput placeholder={t('command.palette.searchPlaceholder')} value={query} onValueChange={setQuery} />
      <CommandList>
        <CommandEmpty>{t('command.palette.noCommands')}</CommandEmpty>
        {extraGroups.map(([group, items]) => (
          <CommandGroup key={`extra-${group}`} heading={t(`command.palette.groups.${group}`, { defaultValue: group })}>
            {items.map((cmd) => (
              <CommandItem
                key={cmd.id}
                value={`${cmd.group} ${cmd.label}`}
                onSelect={() => executeExtra(cmd)}
              >
                <span className="flex-1">{cmd.label}</span>
                {cmd.shortcut ? (
                  <span className="text-[10px] text-muted-foreground">{cmd.shortcut}</span>
                ) : null}
              </CommandItem>
            ))}
          </CommandGroup>
        ))}
        {groups.map(([group, items]) => (
          <CommandGroup key={group} heading={t(`command.palette.groups.${group}`, { defaultValue: group })}>
            {items.map((cmd) => (
              <CommandItem
                key={cmd.id}
                value={`${cmd.group} ${cmd.label} ${t(`command.palette.commands.${cmd.id}`, { defaultValue: cmd.label })}`}
                onSelect={() => execute(cmd)}
              >
                <span className="flex-1">{t(`command.palette.commands.${cmd.id}`, { defaultValue: cmd.label })}</span>
                {cmd.shortcut ? (
                  <span className="text-[10px] text-muted-foreground">{cmd.shortcut}</span>
                ) : null}
              </CommandItem>
            ))}
          </CommandGroup>
        ))}
      </CommandList>
    </CommandDialog>
  )
}
