import type { TFunction } from 'i18next'

import type { KitableTemplateSeed } from './kitableTemplates'

export function createTaskTrackerTemplate(
  t: TFunction<'table'>,
): KitableTemplateSeed {
  return {
    id: 'task-tracker',
    title: t('templateLibrary.templates.taskTracker.title'),
    description: t('templateLibrary.templates.taskTracker.description'),
    documentDescription: 'Track delivery progress, ownership, important work, and completion dates.',
    usageCount: 8228,
    preview: 'task-tracker',
    icon: 'check-square',
    color: 'violet',
    tables: [{
      title: 'Task Management',
      description: 'Task delivery details, ownership, progress, dates, and status updates.',
      fields: [
        { title: 'Task Description', name: 'task_description', type: 'text', primary: true },
        { title: 'Task Summary', name: 'task_summary', type: 'text' },
        { title: 'Assignee', name: 'assignee', type: 'text' },
        {
          title: 'Progress',
          name: 'progress',
          type: 'single_select',
          options: { choices: ['Completed', 'In Progress', 'Not Started'] },
        },
        {
          title: 'Start Date',
          name: 'start_date',
          type: 'date',
          options: { date_format: 'year_month_day_dash' },
        },
        {
          title: 'Expected Completion Date',
          name: 'expected_completion_date',
          type: 'date',
          options: { date_format: 'year_month_day_dash' },
        },
        {
          title: 'Actual Completion Date',
          name: 'actual_completion_date',
          type: 'date',
          options: { date_format: 'year_month_day_dash' },
        },
        { title: 'Important', name: 'important', type: 'checkbox' },
        { title: 'Latest Progress Update', name: 'latest_progress_update', type: 'text' },
        { title: 'Notes', name: 'notes', type: 'text' },
      ],
      views: [{
        title: 'Grid view',
        type: 'grid',
        config: {
          group_field_name: 'progress',
          group_items: [{ field_name: 'progress', direction: 'asc' }],
          frozen_column_count: 1,
        },
      }],
      records: [
        {
          'Task Description': 'User Requirement Research',
          'Task Summary': 'Collect and analyze user feedback',
          Assignee: 'Michael',
          Progress: 'In Progress',
          'Start Date': '2024-11-01',
          'Expected Completion Date': '2024-11-10',
          'Actual Completion Date': '2024-11-08',
          Important: true,
          'Latest Progress Update': 'Completed survey analysis and submitted report',
          Notes: 'Sync results with marketing team',
        },
        {
          'Task Description': 'Product Feature Design',
          'Task Summary': 'Design core product feature prototype',
          Assignee: 'Sarah',
          Progress: 'In Progress',
          'Start Date': '2024-11-05',
          'Expected Completion Date': '2024-11-15',
          'Actual Completion Date': '2024-11-14',
          'Latest Progress Update': 'Prototype passed internal review',
          Notes: 'Prepare for user testing',
        },
        {
          'Task Description': 'Frontend UI Development',
          'Task Summary': 'Develop homepage and login UI',
          Assignee: 'James',
          Progress: 'In Progress',
          'Start Date': '2024-11-10',
          'Expected Completion Date': '2025-12-17',
          Important: true,
          'Latest Progress Update': 'Homepage 90% done',
          Notes: 'Important and urgent',
        },
        {
          'Task Description': 'Backend API Development',
          'Task Summary': 'Develop registration and login APIs',
          Assignee: 'David',
          Progress: 'Completed',
          'Start Date': '2024-11-08',
          'Expected Completion Date': '2024-11-20',
          'Actual Completion Date': '2024-11-18',
          Important: true,
          'Latest Progress Update': 'APIs deployed to test environment',
          Notes: 'Coordinate with frontend for testing',
        },
        {
          'Task Description': 'Database Design',
          'Task Summary': 'Design user data table structure',
          Assignee: 'Sophia',
          Progress: 'Completed',
          'Start Date': '2024-11-03',
          'Expected Completion Date': '2024-11-12',
          'Actual Completion Date': '2024-11-10',
          'Latest Progress Update': 'Table structure designed and approved',
          Notes: 'Optimize query performance later',
        },
        {
          'Task Description': 'User Testing Plan',
          'Task Summary': 'Create test plan and cases',
          Assignee: 'Jessica',
          Progress: 'In Progress',
          'Start Date': '2024-11-15',
          'Expected Completion Date': '2024-11-28',
          Important: true,
          'Latest Progress Update': 'Test cases 50% complete',
          Notes: 'Speed up to meet launch timeline',
        },
        {
          'Task Description': 'Competitor Analysis',
          'Task Summary': 'Analyze main competitor products',
          Assignee: 'Nicole',
          Progress: 'Completed',
          'Start Date': '2024-11-02',
          'Expected Completion Date': '2024-11-09',
          'Actual Completion Date': '2024-11-10',
          'Latest Progress Update': 'Submitted competitor analysis report',
          Notes: 'Discuss differentiation with product team',
        },
        {
          'Task Description': 'Product Logo Design',
          'Task Summary': 'Design company and product logo',
          Assignee: 'Alex',
          Progress: 'Completed',
          'Start Date': '2024-11-06',
          'Expected Completion Date': '2024-11-13',
          'Actual Completion Date': '2024-11-12',
          Important: true,
          'Latest Progress Update': 'Logo finalized and delivered',
          Notes: 'Register trademark',
        },
        {
          'Task Description': 'Security Testing',
          'Task Summary': 'Test system for security vulnerabilities',
          Assignee: 'Nicole',
          Progress: 'In Progress',
          'Start Date': '2024-11-20',
          'Expected Completion Date': '2024-12-03',
          'Latest Progress Update': 'Initial scan done',
          Notes: 'Important and urgent',
        },
        {
          'Task Description': 'Payment Function Integration',
          'Task Summary': 'Integrate third-party payment gateway',
          Assignee: 'Sophia',
          Progress: 'In Progress',
          'Start Date': '2024-11-12',
          'Expected Completion Date': '2025-12-30',
          Important: true,
          'Latest Progress Update': 'Payment integration 70% done',
          Notes: 'Test various payment scenarios',
        },
        {
          'Task Description': 'Product Launch Preparation',
          'Task Summary': 'Prepare server and domain setup',
          Assignee: 'Sophia',
          Progress: 'Not Started',
          'Start Date': '2024-11-25',
          'Expected Completion Date': '2026-01-21',
          'Latest Progress Update': 'Prepare to purchase cloud services',
          Notes: 'Contact vendor in advance',
        },
        {
          'Task Description': 'Mobile Adaptation',
          'Task Summary': 'Adapt UI for iOS and Android',
          Assignee: 'Matthew',
          Progress: 'In Progress',
          'Start Date': '2024-11-18',
          'Expected Completion Date': '2025-12-31',
          'Latest Progress Update': 'iOS adaptation 80% done',
          Notes: 'Important but not urgent',
        },
        {
          'Task Description': 'User Manual Writing',
          'Task Summary': 'Write product user guide',
          Assignee: 'Lisa',
          Progress: 'Not Started',
          'Start Date': '2024-11-28',
          'Expected Completion Date': '2024-12-15',
          'Latest Progress Update': 'Plan to start next week',
          Notes: 'Confirm features with PM',
        },
        {
          'Task Description': 'Data Analytics Development',
          'Task Summary': 'Develop user behavior analytics module',
          Assignee: 'Matthew',
          Progress: 'In Progress',
          'Start Date': '2024-11-15',
          'Expected Completion Date': '2024-12-01',
          'Latest Progress Update': 'Module 60% complete',
          Notes: 'Sync data interface with backend',
        },
        {
          'Task Description': 'Internal Testing',
          'Task Summary': 'Test all product features',
          Assignee: 'Nicole',
          Progress: 'Completed',
          'Start Date': '2024-11-22',
          'Expected Completion Date': '2024-12-08',
          'Actual Completion Date': '2024-12-09',
          Important: true,
          'Latest Progress Update': 'Testing 30% done',
          Notes: 'Important and urgent',
        },
        {
          'Task Description': 'Promotional Video Creation',
          'Task Summary': 'Create product promo video',
          Assignee: 'Nicole',
          Progress: 'Completed',
          'Start Date': '2024-11-07',
          'Expected Completion Date': '2024-11-16',
          'Actual Completion Date': '2024-11-15',
          Important: true,
          'Latest Progress Update': 'Video uploaded to cloud',
          Notes: 'Submit to marketing team',
        },
        {
          'Task Description': 'Social Media Promotion Plan',
          'Task Summary': 'Plan promotion strategy and content',
          Assignee: 'Amanda',
          Progress: 'Not Started',
          'Start Date': '2024-11-30',
          'Expected Completion Date': '2025-12-31',
          'Latest Progress Update': 'Draft prepared',
          Notes: 'Coordinate materials with designer',
        },
        {
          'Task Description': 'Customer Support System Setup',
          'Task Summary': 'Set up online support system',
          Assignee: 'Robert',
          Progress: 'Not Started',
          'Start Date': '2024-12-01',
          'Expected Completion Date': '2026-01-07',
          'Latest Progress Update': 'Plan to use third-party tool',
          Notes: 'Evaluate tool costs',
        },
        {
          'Task Description': 'Product Iteration Planning',
          'Task Summary': 'Plan next version features',
          Assignee: 'Nicole',
          Progress: 'In Progress',
          'Start Date': '2024-11-25',
          'Expected Completion Date': '2024-12-15',
          'Latest Progress Update': 'Collecting user feedback',
          Notes: 'Brainstorm with team',
        },
        {
          'Task Description': 'Funding Pitch Preparation',
          'Task Summary': 'Prepare PPT for investors',
          Assignee: 'Sophia',
          Progress: 'Completed',
          'Start Date': '2024-11-10',
          'Expected Completion Date': '2024-11-18',
          'Actual Completion Date': '2024-11-17',
          'Latest Progress Update': 'PPT completed and approved',
          Notes: 'Practice presentation',
        },
      ],
    }],
    dashboards: [{
      id: 'task-dashboard',
      title: 'Task Dashboard',
      order: 0,
      source_table_name: 'Task Management',
      layout: [
        { widget_id: 'total-tasks', x: 0, y: 0, w: 3, h: 2, min_w: 2, min_h: 2 },
        { widget_id: 'completed-tasks', x: 3, y: 0, w: 3, h: 2, min_w: 2, min_h: 2 },
        { widget_id: 'important-tasks', x: 6, y: 0, w: 3, h: 2, min_w: 2, min_h: 2 },
        { widget_id: 'not-started-tasks', x: 9, y: 0, w: 3, h: 2, min_w: 2, min_h: 2 },
        { widget_id: 'progress-distribution', x: 0, y: 2, w: 5, h: 4, min_w: 4, min_h: 3 },
        { widget_id: 'assignee-workload', x: 5, y: 2, w: 7, h: 4, min_w: 5, min_h: 3 },
        { widget_id: 'completion-timeline', x: 0, y: 6, w: 5, h: 5, min_w: 4, min_h: 4 },
        { widget_id: 'important-open-tasks', x: 5, y: 6, w: 7, h: 5, min_w: 5, min_h: 4 },
      ],
      widgets: [
        {
          id: 'total-tasks',
          title: 'Total tasks',
          description: 'All tracked work items',
          type: 'metric',
          query: { aggregation: 'count' },
          config: { value_label: 'tasks', color: '#5645d4' },
        },
        {
          id: 'completed-tasks',
          title: 'Completed',
          description: 'Tasks marked complete',
          type: 'metric',
          query: {
            aggregation: 'count',
            filters: [{ field_name: 'progress', operator: 'equals', value: 'Completed' }],
          },
          config: { value_label: 'tasks', color: '#1aae39' },
        },
        {
          id: 'important-tasks',
          title: 'Important',
          description: 'Priority work requiring attention',
          type: 'metric',
          query: { aggregation: 'count_true', field_name: 'important' },
          config: { value_label: 'tasks', color: '#dd5b00' },
        },
        {
          id: 'not-started-tasks',
          title: 'Not started',
          description: 'Tasks waiting to begin',
          type: 'metric',
          query: {
            aggregation: 'count',
            filters: [{ field_name: 'progress', operator: 'equals', value: 'Not Started' }],
          },
          config: { value_label: 'tasks', color: '#787671' },
        },
        {
          id: 'progress-distribution',
          title: 'Progress distribution',
          description: 'Task count by progress state',
          type: 'pie',
          query: { aggregation: 'count', group_by_field_name: 'progress' },
          config: { category_order: ['Completed', 'In Progress', 'Not Started'] },
        },
        {
          id: 'assignee-workload',
          title: 'Tasks by assignee',
          description: 'Current workload across the team',
          type: 'bar',
          query: { aggregation: 'count', group_by_field_name: 'assignee' },
          config: { color: '#5645d4' },
        },
        {
          id: 'completion-timeline',
          title: 'Completion timeline',
          description: 'Completed tasks by actual completion date',
          type: 'line',
          query: {
            aggregation: 'count',
            group_by_field_name: 'actual_completion_date',
            filters: [{ field_name: 'progress', operator: 'equals', value: 'Completed' }],
          },
          config: { color: '#2a9d99' },
        },
        {
          id: 'important-open-tasks',
          title: 'Important open tasks',
          description: 'Important work that is not completed',
          type: 'table',
          query: {
            aggregation: 'count',
            filters: [
              { field_name: 'important', operator: 'truthy' },
              { field_name: 'progress', operator: 'not_equals', value: 'Completed' },
            ],
            columns: ['task_description', 'assignee', 'progress', 'expected_completion_date'],
            limit: 8,
          },
        },
      ],
    }],
  }
}
