import { act, createElement } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { ActionPropertiesPanel } from './ActionPropertiesPanel'
import type { TableSchema } from './BodyTemplateEditor.types'

vi.mock('@/services/desktop', () => ({ resolveApiURL: (p: string) => `http://test${p}` }))

let container: HTMLDivElement; let root: Root | null = null

async function mount(node: ReturnType<typeof createElement>) {
  await act(async () => { root = createRoot(container); root.render(node); await Promise.resolve() })
}

beforeEach(() => {
  container = document.createElement('div'); document.body.appendChild(container)
})
afterEach(() => { root?.unmount(); container.remove(); vi.restoreAllMocks() })

const schema: TableSchema = { id: 'tbl', name: 'Leads', fields: [{ id: 'fld_a', name: 'First Name', type: 'text' }] }
const action = {
  nodeId: 'n2', type: 'send_email' as const, to: 'sales@x.com', subject: { parts: [{ kind: 'text' as const, text: 'New Lead' }] }, body: {
    parts: [
      { kind: 'text' as const, text: 'Name: ' },
      { kind: 'field_ref' as const, fieldRef: { nodeId: 'n1', fieldId: 'fld_a' } },
    ],
  },
}

describe('ActionPropertiesPanel', () => {
  it('renders To, Subject, Body with chip', async () => {
    await mount(createElement(ActionPropertiesPanel, {
      workflowId: 'auto_1', action, schema, triggerNodeTitle: '1. When record...', onClose: () => {},
    }))
    const toInput = container.querySelector('[data-testid="props-to"]') as HTMLInputElement | null
    expect(toInput?.value).toBe('sales@x.com')
    expect(container.textContent).toContain('New Lead')
    expect(container.querySelectorAll('[data-testid="field-ref-chip"]').length).toBe(1)
  })

  it('shows preview results after dry-run succeeds', async () => {
    global.fetch = vi.fn(() => Promise.resolve(new Response(JSON.stringify({
      ok: true, input: { to: 'sales@x.com', subject: 'New Lead', body: 'Name: Sample John' },
    }), { headers: { 'content-type': 'application/json' } }))) as unknown as typeof fetch
    await mount(createElement(ActionPropertiesPanel, {
      workflowId: 'auto_1', action, schema, triggerNodeTitle: '1. When record...', onClose: () => {},
    }))
    await act(async () => {
      container.querySelector('[data-testid="run-test-btn"]')?.dispatchEvent(new MouseEvent('click', { bubbles: true }))
      await Promise.resolve()
      await Promise.resolve()
    })
    // Renamed from "Step successful" → "Preview generated" so the label no longer
    // overstates what a dry-run does (it doesn't actually send). Audit #27.
    expect(container.querySelector('[data-testid="dry-run-status"]')?.textContent).toContain('Preview generated')
    expect(container.textContent).toContain('Sample John')
  })

  it('calls onClose when × is clicked', async () => {
    const onClose = vi.fn()
    await mount(createElement(ActionPropertiesPanel, {
      workflowId: 'auto_1', action, schema, triggerNodeTitle: '1. When record...', onClose,
    }))
    container.querySelector('[data-testid="props-close"]')?.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    expect(onClose).toHaveBeenCalledOnce()
  })

  it('renders an accurate edit affordance instead of the old "body can only be regenerated" claim', async () => {
    // Regression guard: the original copy told users to recreate the workflow
    // to change the body. That was false (body is editable on the Home page),
    // so this asserts both the misleading copy is gone and the new handoff is
    // present.
    await mount(createElement(ActionPropertiesPanel, {
      workflowId: 'auto_1', action, schema, triggerNodeTitle: '1. When record...', onClose: () => {},
    }))
    expect(container.textContent).not.toContain('regenerated by recreating')
    const openBtn = container.querySelector('[data-testid="props-open-in-list"]') as HTMLButtonElement | null
    expect(openBtn).not.toBeNull()
    expect(openBtn?.textContent).toMatch(/Open in Workflows to edit/)
  })

  it('handoff button writes the workflowId into history.state and routes to /workflow', async () => {
    // The handoff is what makes the new copy honest: clicking it lands the user
    // on the Home page with this workflow pre-selected, so they don't have to
    // hunt for it. Verify the helper wrote selectedWorkflowId before popstate
    // fires (Shell remounts the route on popstate, so order matters).
    window.history.replaceState({}, '', '/workflow/new')
    const pushSpy = vi.spyOn(window.history, 'pushState')

    await mount(createElement(ActionPropertiesPanel, {
      workflowId: 'auto_42', action, schema, triggerNodeTitle: '1. When record...', onClose: () => {},
    }))
    container.querySelector('[data-testid="props-open-in-list"]')?.dispatchEvent(new MouseEvent('click', { bubbles: true }))

    const call = pushSpy.mock.calls.at(-1)!
    expect(call[0]).toMatchObject({ selectedWorkflowId: 'auto_42' })
    expect(call[2]).toBe('/workflow')
  })
})
