import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import { BodyTemplateEditor } from './BodyTemplateEditor'
import type { BodyTemplate, TableSchema } from './BodyTemplateEditor.types'
import { useWorkflowDryRun } from '../hooks/useWorkflowDryRun'
import { useWorkflowSendTest } from '../hooks/useWorkflowSendTest'
import { openWorkflowHome } from '../lib/openWorkflowRoute'

export interface ActionPropertiesPanelProps {
  workflowId: string
  action: {
    nodeId: string
    type: 'send_email'
    to: string
    subject: BodyTemplate
    body: BodyTemplate
  }
  schema: TableSchema
  triggerNodeTitle: string
  onClose: () => void
}

/**
 * Read-only inspector for the AI-generated email action.
 *
 * Previously this panel showed CC / BCC / Sender Name / Reply To / Custom Email
 * Server controls — all `readOnly` and `disabled`, all faking editability with
 * "Type $ to select value" placeholders. Those were stripped: the panel now
 * mirrors what the workflow actually does (To, Subject, Body), with a
 * one-click handoff to the Workflows list where every field is editable.
 *
 * History note: the explanatory text used to claim "the body template can only
 * be regenerated by recreating the workflow." That was a leftover from when
 * Home was a read-only body preview — Home now mounts `BodyTemplateEditor`
 * editable (see `WorkflowHomePage.tsx`), so the text was misleading users
 * into recreating workflows they could just edit in place. The current copy
 * + button send them straight to the editable view.
 *
 * The test step is split into two clearly-labeled actions:
 *  1. **Preview action** — renders a sample row through the body template, no
 *     email is sent. Replaces the old misnamed "Run Test" that produced a
 *     "✓ Step successful" card without ever sending anything (audit #27).
 *  2. **Send real test email** — actually delivers through the configured SMTP
 *     sender to a recipient the user chooses (defaults to the workflow's To).
 *     Subject is prefixed with [TEST] server-side.
 */
export function ActionPropertiesPanel({ workflowId, action, schema, triggerNodeTitle, onClose }: ActionPropertiesPanelProps) {
  const { t } = useTranslation('workflow')
  const dryRun = useWorkflowDryRun()
  const sendTest = useWorkflowSendTest()
  const [configOpen, setConfigOpen] = useState(true)
  const [testOpen, setTestOpen] = useState(true)
  const [testTo, setTestTo] = useState('')
  const panelRef = useRef<HTMLDivElement | null>(null)

  // Keyboard escape: matches the rest of the app's overlay conventions.
  useEffect(() => {
    panelRef.current?.focus()
    function onKey(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        event.stopPropagation()
        onClose()
      }
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onClose])

  const testToValidates = testTo === '' || /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(testTo)
  const sendDisabled = sendTest.status === 'running' || !testToValidates

  return (
    <div
      data-testid="action-properties-panel"
      ref={panelRef}
      role="dialog"
      tabIndex={-1}
      aria-label={t('panels.action.panelAria')}
      className="fixed right-0 top-0 z-50 h-full w-[440px] overflow-y-auto border-l border-border bg-card p-4 shadow-[-8px_0_16px_rgba(0,0,0,0.08)] focus:outline-none"
    >
      <header className="mb-3 flex items-center justify-between">
        <div className="text-sm font-semibold">{t('panels.action.headerTitle')}</div>
        <button
          data-testid="props-close"
          onClick={onClose}
          aria-label={t('panels.action.closeAria')}
          className="bg-transparent text-lg leading-none text-muted-foreground hover:text-foreground"
        >
          ×
        </button>
      </header>

      {/* The previous note here claimed the body template "can only be regenerated by
          recreating the workflow", which was false — `WorkflowHomePage` mounts
          `BodyTemplateEditor` with readOnly={false} so all three fields (To, Subject,
          Body) are editable from the Workflows list. Replaced with an accurate
          one-line summary plus a button that jumps straight to that list with this
          workflow pre-selected, so the user doesn't have to navigate by hand. */}
      <div className="mb-3 rounded-md border border-border bg-muted/40 px-3 py-2 text-[11px] leading-relaxed text-muted-foreground">
        <div>{t('panels.action.previewNote')}</div>
        <button
          type="button"
          data-testid="props-open-in-list"
          onClick={() => openWorkflowHome({ workflowId })}
          className="mt-1.5 inline-flex items-center gap-1 rounded-md border border-primary/30 bg-card px-2 py-1 text-[11px] font-medium text-primary hover:bg-primary/15"
        >
          {t('panels.action.openInList')}
          <span aria-hidden>→</span>
        </button>
      </div>

      <Section title={t('panels.action.sectionConfig')} open={configOpen} onToggle={() => setConfigOpen((v) => !v)}>
        <Field label={t('panels.action.labelTo')} required>
          <input
            data-testid="props-to"
            readOnly
            value={action.to}
            placeholder={t('panels.action.noRecipient')}
            className={displayClass}
            tabIndex={-1}
          />
        </Field>
        <Field label={t('panels.action.labelSubject')} required>
          <div data-testid="props-subject" className={displayClass}>
            {action.subject.parts.length === 0 ? (
              <span className="text-muted-foreground/80">{t('panels.action.noSubject')}</span>
            ) : (
              <BodyTemplateEditor template={action.subject} schema={schema} triggerNodeTitle={triggerNodeTitle} triggerNodeId={schema.id} readOnly />
            )}
          </div>
        </Field>
        <Field label={t('panels.action.labelBody')} required>
          <BodyTemplateEditor template={action.body} schema={schema} triggerNodeTitle={triggerNodeTitle} readOnly />
        </Field>
      </Section>

      <Section title={t('panels.action.sectionTest')} open={testOpen} onToggle={() => setTestOpen((v) => !v)}>
        <p className="mb-2 text-xs text-muted-foreground">
          {t('panels.action.testIntro')}
        </p>
        <button
          data-testid="run-test-btn"
          onClick={() => { void dryRun.run(workflowId) }}
          disabled={dryRun.status === 'running'}
          className="w-full rounded-lg border border-border bg-card py-2 text-sm text-foreground hover:bg-muted/40 disabled:opacity-60"
        >
          {dryRun.status === 'running' ? t('panels.action.previewing') : t('panels.action.previewBtn')}
        </button>

        <div className="mt-3 border-t border-border pt-3">
          <label className="mb-1 block text-xs font-medium text-foreground" htmlFor="send-test-to">
            {t('panels.action.sendToLabel')}
          </label>
          <input
            id="send-test-to"
            data-testid="send-test-to"
            type="email"
            value={testTo}
            onChange={(e) => setTestTo(e.target.value)}
            placeholder={action.to || t('panels.action.sendToPlaceholder')}
            className="mb-2 w-full rounded-md border border-border bg-card px-2 py-1.5 text-[13px] outline-none focus:border-ring"
          />
          {!testToValidates ? (
            <div className="mb-2 text-[11px] text-destructive">{t('panels.action.invalidEmail')}</div>
          ) : (
            <div className="mb-2 text-[11px] text-muted-foreground">{t('panels.action.blankHint', { to: action.to })}</div>
          )}
          <button
            data-testid="send-test-btn"
            onClick={() => { void sendTest.send(workflowId, testTo) }}
            disabled={sendDisabled}
            className="w-full rounded-lg border-0 bg-primary py-2.5 text-sm text-primary-foreground hover:bg-primary/90 disabled:opacity-60"
          >
            {sendTest.status === 'running' ? t('panels.action.sending') : t('panels.action.sendBtn')}
          </button>
        </div>
      </Section>

      {dryRun.status === 'done' && dryRun.result ? (
        <Section title={t('panels.action.sectionPreviewResult')} open onToggle={() => {}}>
          <div data-testid="dry-run-status" className="mb-1 font-semibold text-foreground">{t('panels.action.previewGenerated')} <span className="text-muted-foreground">{t('panels.action.previewNoEmail')}</span></div>
          <div className="mb-3 text-xs text-muted-foreground">{t('panels.action.renderedJustNow')}</div>
          <div className="mb-1 text-xs font-semibold">{t('panels.action.renderedInput')}</div>
          <div className="text-xs leading-relaxed">
            <div><strong>{t('panels.action.labelTo')}</strong>&nbsp;&nbsp;{dryRun.result.input.to}</div>
            <div><strong>{t('panels.action.labelSubject')}</strong>&nbsp;&nbsp;{dryRun.result.input.subject}</div>
            <div data-testid="dry-run-body" className="mt-1.5 whitespace-pre-wrap"><strong>{t('panels.action.labelBody')}</strong>&nbsp;&nbsp;{dryRun.result.input.body}</div>
          </div>
        </Section>
      ) : null}
      {dryRun.status === 'error' ? (
        <div data-testid="dry-run-error" className="mt-2 text-sm text-destructive">✕ {dryRun.error}</div>
      ) : null}

      {sendTest.status === 'done' && sendTest.result ? (
        <Section title={t('panels.action.sectionTestSent')} open onToggle={() => {}}>
          <div data-testid="send-test-status" className="mb-1 font-semibold text-success">{t('panels.action.testDelivered')}</div>
          <div className="mb-3 text-xs text-muted-foreground">{t('panels.action.sentJustNow', { to: sendTest.result.input.to })}</div>
          <div className="text-xs leading-relaxed">
            <div><strong>{t('panels.action.labelTo')}</strong>&nbsp;&nbsp;{sendTest.result.input.to}</div>
            <div><strong>{t('panels.action.labelSubject')}</strong>&nbsp;&nbsp;{sendTest.result.input.subject}</div>
            <div data-testid="send-test-body" className="mt-1.5 whitespace-pre-wrap"><strong>{t('panels.action.labelBody')}</strong>&nbsp;&nbsp;{sendTest.result.input.body}</div>
          </div>
        </Section>
      ) : null}
      {sendTest.status === 'error' ? (
        <div data-testid="send-test-error" className="mt-2 text-sm text-destructive">✕ {sendTest.error}</div>
      ) : null}
    </div>
  )
}

const displayClass = 'min-h-[30px] w-full rounded-md border border-border bg-muted/40 px-2 py-1.5 text-[13px] text-foreground'

function Field({ label, required, children }: { label: string; required?: boolean; children: ReactNode }) {
  return (
    <div className="mb-3">
      <div className="mb-1 text-xs font-medium">
        {required ? <span className="mr-1 text-destructive">*</span> : null}
        {label}
      </div>
      {children}
    </div>
  )
}

function Section({ title, open, onToggle, children }: { title: string; open: boolean; onToggle: () => void; children: ReactNode }) {
  return (
    <section className="mt-3">
      <button
        onClick={onToggle}
        className="flex w-full justify-between border-0 bg-transparent py-2 text-xs font-semibold text-foreground"
      >
        <span className="uppercase tracking-wide text-muted-foreground">{title}</span>
        <span>{open ? '▾' : '▸'}</span>
      </button>
      {open ? <div>{children}</div> : null}
    </section>
  )
}
